=== gonzalorf/dnd-srd/schemas/es/classes.schema.json
{
 "$schema": "https://json-schema.org/draft/2020-12/schema",
 "title": "classes",
 "description": "Inferido de 12 fichas de la colección «classes».",
 "type": "array",
 "items": {
  "type": "object",
  "properties": {
   "coreTraits": {
    "type": "object",
    "properties": {
     "Característica principal": {
      "type": "string",
      "enum": [
       "Carisma",
       "Destreza",
       "Destreza y Sabiduría",
       "Fuerza",
       "Fuerza o Destreza",
       "Fuerza y Carisma",
       "Inteligencia",
       "Sabiduría"
      ]
     },
     "Competencias con armas": {
      "type": "string",
      "enum": [
       "Amas sencillas",
       "Armas sencillas",
       "Armas sencillas y marciales",
       "Armas sencillas, además de marciales que tengan la propiedad “ligera”",
       "Armas sencillas, además de marciales que tengan las propiedades “ligera” o “sutil”"
      ]
     },
     "Competencias con herramientas": {
      "type": "string",
      "enum": [
       "Elige tres instrumentos musicales (consulta el capítulo “Equipo”)",
       "Elige un tipo de herramientas de artesano o instrumento musical (consulta el capítulo “Equipo”)",
       "Herramientas de ladrón",
       "Útiles de herborista"
      ]
     },
     "Competencias en habilidades": {
      "type": "string",
      "enum": [
       "Elige cuatro: Acrobacias, Atletismo, Engaño, Intimidación, Investigación, Juego de manos, Percepción, Perspicacia, Persuasión o Sigilo",
       "Elige dos: Acrobacias, Atletismo, Historia, Intimidación, Percepción, Perspicacia, Persuasión, Supervivencia o Trato con animales",
       "Elige dos: Acrobacias, Atletismo, Historia, Perspicacia, Religión o Sigilo",
       "Elige dos: Atletismo, Intimidación, Medicina, Perspicacia, Persuasión o Religión",
       "Elige dos: Atletismo, Intimidación, Naturaleza, Percepción, Supervivencia o Trato con animales",
       "Elige dos: Conocimiento arcano, Engaño, Historia, Intimidación, Investigación, Naturaleza o Religión",
       "Elige dos: Conocimiento arcano, Engaño, Intimidación, Perspicacia, Persuasión o Religión",
       "Elige dos: Conocimiento arcano, Historia, Investigación, Medicina, Naturaleza, Perspicacia o Religión",
       "Elige dos: Conocimiento arcano, Medicina, Naturaleza, Percepción, Perspicacia, Religión, Supervivencia o Trato con animales",
       "Elige dos: Historia, Medicina, Perspicacia, Persuasión o Religión",
       "Elige tres cualesquiera (consulta el capítulo “Cómo jugar”)",
       "Elige tres: Atletismo, Investigación, Naturaleza, Percepción, Perspicacia, Sigilo, Supervivencia o Trato con animales"
      ]
     },
     "Competencias en tiradas de salvación": {
      "type": "string",
      "enum": [
       "Constitución y Carisma",
       "Destreza e Inteligencia",
       "Destreza y Carisma",
       "Fuerza y Constitución",
       "Fuerza y Destreza",
       "Inteligencia y Sabiduría",
       "Sabiduría y Carisma"
      ]
     },
     "Dado de puntos de golpe": {
      "type": "string",
      "enum": [
       "1d10 por nivel de Paladín",
       "1d10 por nivel de explorador",
       "1d10 por nivel de guerrero",
       "1d12 por nivel de bárbaro",
       "1d6 por nivel de hechicero",
       "1d6 por nivel de mago",
       "1d8 por nivel de bardo",
       "1d8 por nivel de brujo",
       "1d8 por nivel de clérigo",
       "1d8 por nivel de druida",
       "1d8 por nivel de monje",
       "1d8 por nivel de pícaro"
      ]
     },
     "Entrenamiento con armaduras": {
      "type": "string",
      "enum": [
       "Armaduras ligeras",
       "Armaduras ligeras y escudos",
       "Armaduras ligeras y medias y escudos",
       "Armaduras ligeras, medias y pesadas y escudos",
       "Ninguna"
      ]
     },
     "Equipo inicial": {
      "type": "string",
      "enum": [
       "Elige A o B: (A) 2 dagas, canalizador arcano (bastón), libro de conjuros, paquete de erudito, túnica y 5 po, o (B) 55 po",
       "Elige A o B: (A) armadura de",
       "Elige A o B: (A) armadura de cuero tachonado, cimitarra, espada corta, arco largo, 20 flechas, aljaba, canalizador druídico (rama de muérdago), paquete de explorador y 7 po, o (B) 150 po",
       "Elige A o B: (A) armadura de cuero, hoz, 2 dagas, canalizador arcano (orbe), libro (de conocimiento oculto), paquete de erudito y 15 po, o (B) 100 po",
       "Elige A o B: (A) camisa de malla, escudo, maza, paquete de sacerdote, símbolo sagrado y 7 po, o (B) 110 po",
       "Elige A o B: (A) cota de malla, escudo, espada larga, 6 jabalinas, símbolo sagrado, paquete de sacerdote y 9 po, o (B) 150 po",
       "Elige A o B: (A) hacha a dos manos, 4 hachas de mano, paquete de explorador y 15 po, o (B) 75 po",
       "Elige A o B: (A) lanza, 2 dagas, canalizador arcano (cristal), paquete de explorador de mazmorras y 28 po, o (B) 50 po",
       "Elige A o B: (A) lanza, 5 dagas,",
       "Elige A, Bo C: (A) cota de malla, espadón, mangual, 8 jabalinas, paquete de explorador de mazmorras y 4 po; (B) armadura de cuero tachonado, cimitarra, espada corta, arco largo, 20 flechas, aljaba, paquete de explorador de mazmorras y 11 po, o (C) 155 po"
      ]
     }
    },
    "required": [
     "Característica principal",
     "Competencias con armas",
     "Competencias en habilidades",
     "Competencias en tiradas de salvación",
     "Dado de puntos de golpe",
     "Entrenamiento con armaduras",
     "Equipo inicial"
    ]
   },
   "features": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "blocks": {
       "type": "array",
       "items": {
        "type": "object",
        "properties": {
         "caption": {
          "type": "string",
          "enum": [
           "Crear espacios de conjuro",
           "Formas de bestia",
           "Rasgos de bárbaro",
           "Rasgos de guerrero",
           "Rasgos de hechicero"
          ]
         },
         "header": {
          "type": "array",
          "items": {
           "type": "string"
          }
         },
         "md": {
          "type": "string"
         },
         "page": {
          "type": "integer"
         },
         "rows": {
          "type": "array",
          "items": {
           "type": "array",
           "items": {
            "type": "string"
           }
          }
         },
         "text": {
          "type": "string"
         },
         "type": {
          "type": "string",
          "enum": [
           "definition",
           "list-item",
           "paragraph",
           "sidebar",
           "table"
          ]
         }
        },
        "required": [
         "page",
         "type"
        ]
       }
      },
      "level": {
       "type": "integer"
      },
      "name": {
       "type": "string"
      },
      "page": {
       "type": "integer"
      },
      "subclass": {
       "type": "null"
      },
      "text": {
       "type": "string"
      },
      "title": {
       "type": "string"
      }
     },
     "required": [
      "blocks",
      "level",
      "name",
      "page",
      "subclass",
      "text",
      "title"
     ]
    }
   },
   "id": {
    "type": "string",
    "enum": [
     "class.barbaro",
     "class.bardo",
     "class.brujo",
     "class.clerigo",
     "class.druida",
     "class.explorador",
     "class.guerrero",
     "class.hechicero",
     "class.mago",
     "class.monje",
     "class.paladin",
     "class.picaro"
    ]
   },
   "name": {
    "type": "string",
    "enum": [
     "Bardo",
     "Brujo",
     "Bárbaro",
     "Clérigo",
     "Druida",
     "Explorador",
     "Guerrero",
     "Hechicero",
     "Mago",
     "Monje",
     "Paladín",
     "Pícaro"
    ]
   },
   "progression": {
    "type": "object",
    "properties": {
     "caption": {
      "type": "string",
      "enum": [
       "Rasgos de bardo",
       "Rasgos de brujo",
       "Rasgos de bárbaro",
       "Rasgos de clérigo",
       "Rasgos de druida",
       "Rasgos de explorador",
       "Rasgos de guerrero",
       "Rasgos de hechicero",
       "Rasgos de mago",
       "Rasgos de monje",
       "Rasgos de paladín",
       "Rasgos de pícaro"
      ]
     },
     "header": {
      "type": "array",
      "items": {
       "type": "string"
      }
     },
     "rows": {
      "type": "array",
      "items": {
       "type": "array",
       "items": {
        "type": "string"
       }
      }
     }
    },
    "required": [
     "caption",
     "header",
     "rows"
    ]
   },
   "refs": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "source": {
    "type": "object",
    "properties": {
     "book": {
      "type": "string",
      "enum": [
       "SRD 5.2.1 es"
      ]
     },
     "page": {
      "type": "integer"
     }
    },
    "required": [
     "book",
     "page"
    ]
   },
   "spellLists": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "caption": {
       "type": "string"
      },
      "header": {
       "type": "array",
       "items": {
        "type": "string",
        "enum": [
         "Conjuro",
         "Escuela",
         "Especial"
        ]
       }
      },
      "level": {
       "type": "integer"
      },
      "page": {
       "type": "integer"
      },
      "rows": {
       "type": "array",
       "items": {
        "type": "array",
        "items": {
         "type": "string"
        }
       }
      }
     },
     "required": [
      "caption",
      "header",
      "level",
      "page",
      "rows"
     ]
    }
   },
   "subclasses": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "features": {
       "type": "array",
       "items": {
        "type": "object",
        "properties": {
         "blocks": {
          "type": "array",
          "items": {
           "type": "object",
           "properties": {
            "caption": {
             "type": "string",
             "enum": [
              "Conjuros del dominio de la vida",
              "Conjuros del infernal",
              "Conjuros del juramento de entrega",
              "Conjuros dracónicos",
              "Protección de la naturaleza",
              "Terreno polar",
              "Terreno templado",
              "Terreno tropical",
              "Terreno árido"
             ]
            },
            "header": {
             "type": "array",
             "items": {
              "type": "string",
              "enum": [
               "Conjuros",
               "Conjuros de círculo",
               "Conjuros preparados",
               "Nivel de brujo",
               "Nivel de clérigo",
               "Nivel de druida",
               "Nivel de hechicero",
               "Nivel de paladín",
               "Resistencia",
               "Tipo de terreno"
              ]
             }
            },
            "md": {
             "type": "string"
            },
            "page": {
             "type": "integer"
            },
            "rows": {
             "type": "array",
             "items": {
              "type": "array",
              "items": {
               "type": "string"
              }
             }
            },
            "text": {
             "type": "string"
            },
            "type": {
             "type": "string",
             "enum": [
              "definition",
              "paragraph",
              "property",
              "table"
             ]
            }
           },
           "required": [
            "page",
            "type"
           ]
          }
         },
         "level": {
          "type": "integer"
         },
         "name": {
          "type": "string"
         },
         "page": {
          "type": "integer"
         },
         "subclass": {
          "type": "string",
          "enum": [
           "Subclase de bardo: Colegio del conocimiento",
           "Subclase de brujo: Patrón infernal",
           "Subclase de bárbaro: Senda del berserker",
           "Subclase de clérigo: Dominio de la vida",
           "Subclase de druida: Círculo de la tierra",
           "Subclase de explorador: Cazador",
           "Subclase de guerrero: Campeón",
           "Subclase de hechicero: Hechicería dracónica",
           "Subclase de mago: Evocador",
           "Subclase de monje: Guerrero de la mano abierta",
           "Subclase de paladín: Juramento de entrega",
           "Subclase de pícaro: Ladrón"
          ]
         },
         "text": {
          "type": "string"
         },
         "title": {
          "type": "string"
         }
        },
        "required": [
         "blocks",
         "level",
         "name",
         "page",
         "subclass",
         "text",
         "title"
        ]
       }
      },
      "name": {
       "type": "string",
       "enum": [
        "Subclase de bardo: Colegio del conocimiento",
        "Subclase de brujo: Patrón infernal",
        "Subclase de bárbaro: Senda del berserker",
        "Subclase de clérigo: Dominio de la vida",
        "Subclase de druida: Círculo de la tierra",
        "Subclase de explorador: Cazador",
        "Subclase de guerrero: Campeón",
        "Subclase de hechicero: Hechicería dracónica",
        "Subclase de mago: Evocador",
        "Subclase de monje: Guerrero de la mano abierta",
        "Subclase de paladín: Juramento de entrega",
        "Subclase de pícaro: Ladrón"
       ]
      }
     },
     "required": [
      "features",
      "name"
     ]
    }
   }
  },
  "required": [
   "coreTraits",
   "features",
   "id",
   "name",
   "progression",
   "source",
   "spellLists",
   "subclasses"
  ]
 }
}

=== gonzalorf/dnd-srd/data/processed/es/collections/classes/paladin.json
{
 "id": "class.paladin",
 "name": "Paladín",
 "coreTraits": {
  "Característica principal": "Fuerza y Carisma",
  "Dado de puntos de golpe": "1d10 por nivel de Paladín",
  "Competencias en tiradas de salvación": "Sabiduría y Carisma",
  "Competencias en habilidades": "Elige dos: Atletismo, Intimidación, Medicina, Perspicacia, Persuasión o Religión",
  "Competencias con armas": "Armas sencillas y marciales",
  "Entrenamiento con armaduras": "Armaduras ligeras, medias y pesadas y escudos",
  "Equipo inicial": "Elige A o B: (A) cota de malla, escudo, espada larga, 6 jabalinas, símbolo sagrado, paquete de sacerdote y 9 po, o (B) 150 po"
 },
 "progression": {
  "caption": "Rasgos de paladín",
  "header": [
   "Nivel",
   "Bonificador por competencia",
   "Rasgos de clase",
   "Canalizar Conjuros divinidadpreparados",
   "Espacios de conjuro por cada nivel de conjuro 12345"
  ],
  "rows": [
   [
    "1",
    "+2",
    "Imponer las manos, Lanzamiento de conjuros, Maestría con armas",
    "—2",
    "2————"
   ],
   [
    "2",
    "+2",
    "Castigo de paladín, Estilo de combate",
    "—3",
    "2————"
   ],
   [
    "3",
    "+2",
    "Canalizar divinidad, subclase de paladín",
    "24",
    "3————"
   ],
   [
    "4",
    "+2",
    "Mejora de característica",
    "25",
    "3————"
   ],
   [
    "5",
    "+3",
    "Ataque adicional, Corcel fiel",
    "26",
    "42———"
   ],
   [
    "6",
    "+3",
    "Aura de protección",
    "26",
    "42———"
   ],
   [
    "7",
    "+3",
    "Rasgo de subclase",
    "27",
    "43———"
   ],
   [
    "8",
    "+3",
    "Mejora de característica",
    "27",
    "43———"
   ],
   [
    "9",
    "+4",
    "Abjurar de los enemigos",
    "29",
    "432——"
   ],
   [
    "10",
    "+4",
    "Aura de coraje",
    "29",
    "432——"
   ],
   [
    "11",
    "+4",
    "Golpes radiantes",
    "310",
    "433——"
   ],
   [
    "12",
    "+4",
    "Mejora de característica",
    "310",
    "433——"
   ],
   [
    "13",
    "+5",
    "—",
    "311",
    "4331—"
   ],
   [
    "14",
    "+5",
    "Toque reparador",
    "311",
    "4331—"
   ],
   [
    "15",
    "+5",
    "Rasgo de subclase",
    "312",
    "4332—"
   ],
   [
    "16",
    "+5",
    "Mejora de característica",
    "312",
    "4332—"
   ],
   [
    "17",
    "+6",
    "—",
    "314",
    "43331"
   ],
   [
    "18",
    "+6",
    "Expansión de aura",
    "314",
    "43331"
   ],
   [
    "19",
    "+6",
    "Don épico",
    "315",
    "43332"
   ],
   [
    "20",
    "+6",
    "Rasgo de subclase",
    "315",
    "43332"
   ]
  ]
 },
 "features": [
  {
   "level": 1,
   "name": "Imponer las manos",
   "title": "Nivel 1: Imponer las manos",
   "subclass": null,
   "text": "Tu toque bendito puede curar heridas. Tienes una reserva de poder de curación que se rellena tras finalizar un descanso largo. Puedes recurrir a esta reserva para restaurar tantos puntos de golpe como cinco veces tu nivel de paladín.\n\nComo acción adicional, puedes tocar a una criatura (que puedes ser tú) y extraer energía de la reserva de curación para hacer que esa criatura recupere una cantidad de puntos de golpe, que como máximo será la cantidad que te quede en dicha reserva.\n\nTambién puedes gastar 5 puntos de golpe de la reserva para eliminar el estado de envenenada de la criatura, pero esos puntos gastados no restaurarán puntos de golpe.",
   "blocks": [
    {
     "type": "paragraph",
     "page": 82,
     "md": "Tu toque bendito puede curar heridas. Tienes una reserva de poder de curación que se rellena tras finalizar un descanso largo. Puedes recurrir a esta reserva para restaurar tantos puntos de golpe como cinco veces tu nivel de paladín.",
     "text": "Tu toque bendito puede curar heridas. Tienes una reserva de poder de curación que se rellena tras finalizar un descanso largo. Puedes recurrir a esta reserva para restaurar tantos puntos de golpe como cinco veces tu nivel de paladín."
    },
    {
     "type": "paragraph",
     "page": 82,
     "md": "Como acción adicional, puedes tocar a una criatura (que puedes ser tú) y extraer energía de la reserva de curación para hacer que esa criatura recupere una cantidad de puntos de golpe, que como máximo será la cantidad que te quede en dicha reserva.",
     "text": "Como acción adicional, puedes tocar a una criatura (que puedes ser tú) y extraer energía de la reserva de curación para hacer que esa criatura recupere una cantidad de puntos de golpe, que como máximo será la cantidad que te quede en dicha reserva."
    },
    {
     "type": "paragraph",
     "page": 82,
     "md": "También puedes gastar 5 puntos de golpe de la reserva para eliminar el estado de envenenada de la criatura, pero esos puntos gastados no restaurarán puntos de golpe.",
     "text": "También puedes gastar 5 puntos de golpe de la reserva para eliminar el estado de envenenada de la criatura, pero esos puntos gastados no restaurarán puntos de golpe."
    }
   ],
   "page": 82
  },
  {
   "level": 1,
   "name": "Lanzamiento de conjuros",
   "title": "Nivel 1: Lanzamiento de conjuros",
   "subclass": null,
   "text": "Has aprendido a lanzar conjuros gracias a la oración y la meditación. Consulta el capítulo “Conjuros” para ver las reglas sobre el lanzamiento de conjuros. La información presentada a continuación detalla cómo usar esas reglas con los conjuros de paladín, que encontrarás más adelante en la lista de conjuros de paladín de la descripción de la clase.\n\nEspacios de conjuro. La tabla “Rasgos de paladín” muestra cuántos espacios de conjuro tienes para lanzar tus conjuros de nivel 1 y superiores. Recuperas todos los espacios utilizados tras finalizar un descanso largo.\n\nConjuros preparados de nivel 1 y superiores. Preparas una serie de conjuros de nivel 1 y superiores, que son los que podrás lanzar con este rasgo. Para empezar, elige dos conjuros de paladín de nivel 1. Se recomiendan castigo abrasador y heroísmo. El número de conjuros de tu lista aumenta conforme subes de nivel de paladín, como se muestra en la columna “Conjuros preparados” de la tabla “Rasgos de paladín”. Cuando ese número aumente, elige conjuros de paladín adicionales hasta que el número de conjuros de tu lista coincida con el número de la tabla “Rasgos de paladín”. Estos conjuros deben ser de un nivel para el que tengas espacios de conjuro. Por ejemplo, si eres un paladín de nivel 5, podrías preparar cualquier combinación de seis conjuros de paladín de nivel 1 o 2. Si otro rasgo de paladín te proporciona conjuros que siempre tienes preparados, esos conjuros no cuentan para el total que puedes preparar con este\n\nrasgo, pero sí que cuentan como conjuros de paladín para ti.\n\nCambiar los conjuros preparados. Tras finalizar un descanso largo, puedes sustituir un conjuro de tu lista por otro conjuro de paladín para el que tengas espacios de conjuro.\n\nAptitud mágica. El Carisma es tu aptitud mágica en lo que respecta a tus conjuros de paladín.\n\nCanalizador mágico. Puedes utilizar un símbolo sagrado como canalizador mágico para tus conjuros de paladín.",
   "blocks": [
    {
     "type": "paragraph",
     "page": 82,
     "md": "Has aprendido a lanzar conjuros gracias a la oración y la meditación. Consulta el capítulo “Conjuros” para ver las reglas sobre el lanzamiento de conjuros. La información presentada a continuación detalla cómo usar esas reglas con los conjuros de paladín, que encontrarás más adelante en la lista de conjuros de paladín de la descripción de la clase.",
     "text": "Has aprendido a lanzar conjuros gracias a la oración y la meditación. Consulta el capítulo “Conjuros” para ver las reglas sobre el lanzamiento de conjuros. La información presentada a continuación detalla cómo usar esas reglas con los conjuros de paladín, que encontrarás más adelante en la lista de conjuros de paladín de la descripción de la clase."
    },
    {
     "type": "definition",
     "page": 82,
     "md": "***Espacios de conjuro.*** La tabla “Rasgos de paladín” muestra cuántos espacios de conjuro tienes para lanzar tus conjuros de nivel 1 y superiores. Recuperas todos los espacios utilizados tras finalizar un descanso largo.",
     "text": "Espacios de conjuro. La tabla “Rasgos de paladín” muestra cuántos espacios de conjuro tienes para lanzar tus conjuros de nivel 1 y superiores. Recuperas todos los espacios utilizados tras finalizar un descanso largo."
    },
    {
     "type": "definition",
     "page": 82,
     "md": "***Conjuros preparados de nivel 1 y superiores.*** Preparas una serie de conjuros de nivel 1 y superiores, que son los que podrás lanzar con este rasgo. Para empezar, elige dos conjuros de paladín de nivel 1. Se recomiendan *castigo abrasador* y *heroísmo*. El número de conjuros de tu lista aumenta conforme subes de nivel de paladín, como se muestra en la columna “Conjuros preparados” de la tabla “Rasgos de paladín”. Cuando ese número aumente, elige conjuros de paladín adicionales hasta que el número de conjuros de tu lista coincida con el número de la tabla “Rasgos de paladín”. Estos conjuros deben ser de un nivel para el que tengas espacios de conjuro. Por ejemplo, si eres un paladín de nivel 5, podrías preparar cualquier combinación de seis conjuros de paladín de nivel 1 o 2. Si otro rasgo de paladín te proporciona conjuros que siempre tienes preparados, esos conjuros no cuentan para el total que puedes preparar con este",
