=== gonzalorf/dnd-srd/schemas/es/monsters.schema.json
{
 "$schema": "https://json-schema.org/draft/2020-12/schema",
 "title": "monsters",
 "description": "Inferido de 336 fichas de la colección «monsters».",
 "type": "array",
 "items": {
  "type": "object",
  "properties": {
   "abilities": {
    "type": "object",
    "properties": {
     "car": {
      "type": "object",
      "properties": {
       "mod": {
        "type": "integer"
       },
       "save": {
        "type": "integer"
       },
       "score": {
        "type": "integer"
       }
      },
      "required": [
       "mod",
       "save",
       "score"
      ]
     },
     "con": {
      "type": "object",
      "properties": {
       "mod": {
        "type": "integer"
       },
       "save": {
        "type": "integer"
       },
       "score": {
        "type": "integer"
       }
      },
      "required": [
       "mod",
       "save",
       "score"
      ]
     },
     "des": {
      "type": "object",
      "properties": {
       "mod": {
        "type": "integer"
       },
       "save": {
        "type": "integer"
       },
       "score": {
        "type": "integer"
       }
      },
      "required": [
       "mod",
       "save",
       "score"
      ]
     },
     "fue": {
      "type": "object",
      "properties": {
       "mod": {
        "type": "integer"
       },
       "save": {
        "type": "integer"
       },
       "score": {
        "type": "integer"
       }
      },
      "required": [
       "mod",
       "save",
       "score"
      ]
     },
     "int": {
      "type": "object",
      "properties": {
       "mod": {
        "type": "integer"
       },
       "save": {
        "type": "integer"
       },
       "score": {
        "type": "integer"
       }
      },
      "required": [
       "mod",
       "save",
       "score"
      ]
     },
     "sab": {
      "type": "object",
      "properties": {
       "mod": {
        "type": "integer"
       },
       "save": {
        "type": "integer"
       },
       "score": {
        "type": "integer"
       }
      },
      "required": [
       "mod",
       "save",
       "score"
      ]
     }
    },
    "required": [
     "car",
     "con",
     "des",
     "fue",
     "int",
     "sab"
    ]
   },
   "ac": {
    "type": "integer"
   },
   "acRaw": {
    "type": "string"
   },
   "actions": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "description": {
       "type": "string"
      },
      "md": {
       "type": "string"
      },
      "name": {
       "type": [
        "string",
        "null"
       ]
      },
      "page": {
       "type": "integer"
      },
      "uses": {
       "type": "string",
       "enum": [
        "1/día",
        "2/día",
        "3/día",
        "recarga 4–6",
        "recarga 5–6",
        "recarga 6"
       ]
      }
     },
     "required": [
      "md",
      "name",
      "page"
     ]
    }
   },
   "alignment": {
    "type": "string"
   },
   "bonusActions": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "description": {
       "type": "string"
      },
      "md": {
       "type": "string"
      },
      "name": {
       "type": [
        "string",
        "null"
       ]
      },
      "page": {
       "type": "integer"
      },
      "uses": {
       "type": "string",
       "enum": [
        "1/día",
        "2/día",
        "3/día",
        "recarga 4–6",
        "recarga 5–6",
        "recarga 6",
        "se recarga tras un descanso corto o largo",
        "solo celestial; se recarga tras un descanso largo",
        "solo feérico; se recarga tras un descanso largo",
        "solo infernal; se recarga tras un descanso largo"
       ]
      }
     },
     "required": [
      "md",
      "name",
      "page"
     ]
    }
   },
   "challenge": {
    "type": "object",
    "properties": {
     "cr": {
      "type": "number"
     },
     "proficiencyBonus": {
      "type": "integer"
     },
     "raw": {
      "type": "string"
     },
     "xp": {
      "type": "integer"
     },
     "xpInLair": {
      "type": "integer"
     }
    },
    "required": [
     "raw"
    ]
   },
   "context": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "gear": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "hp": {
    "type": "object",
    "properties": {
     "average": {
      "type": "integer"
     },
     "formula": {
      "type": "string"
     },
     "raw": {
      "type": "string"
     }
    },
    "required": [
     "raw"
    ]
   },
   "id": {
    "type": "string"
   },
   "immunities": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "initiative": {
    "type": "object",
    "properties": {
     "mod": {
      "type": "integer"
     },
     "score": {
      "type": "integer"
     }
    },
    "required": [
     "mod",
     "score"
    ]
   },
   "languages": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "legendary": {
    "type": "object",
    "properties": {
     "actions": {
      "type": "array",
      "items": {
       "type": "object",
       "properties": {
        "description": {
         "type": "string"
        },
        "md": {
         "type": "string"
        },
        "name": {
         "type": [
          "string",
          "null"
         ]
        },
        "page": {
         "type": "integer"
        }
       },
       "required": [
        "md",
        "name",
        "page"
       ]
      }
     },
     "intro": {
      "type": "string",
      "enum": [
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, el aboleth puede emplear un uso para llevar a cabo una de las siguientes acciones. El aboleth recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, el dragón puede emplear un uso para llevar a cabo una de las siguientes acciones. El dragón recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, el kraken puede emplear un uso para llevar a cabo una de las siguientes acciones. El kraken recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, el liche puede emplear un uso para llevar a cabo una de las siguientes acciones. El liche recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, el vampiro puede emplear un uso para llevar a cabo una de las siguientes acciones. El vampiro recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, la esfinge puede emplear un uso para llevar a cabo una de las siguientes acciones. La esfinge recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, la momia puede emplear un uso para llevar a cabo una de las siguientes acciones. La momia recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3. Justo después del turno de otra criatura, el solar puede emplear un uso para llevar a cabo una de las siguientes acciones. El solar recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3. Justo después del turno de otra criatura, el unicornio puede emplear un uso para llevar a cabo una de las siguientes acciones. El unicornio recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3. Justo después del turno de otra criatura, la tarasca puede emplear un uso para llevar a cabo una de las siguientes acciones. La tarasca recupera todos los usos al principio de cada uno de sus turnos."
      ]
     },
     "uses": {
      "type": "integer"
     },
     "usesInLair": {
      "type": "integer"
     }
    },
    "required": [
     "actions",
     "intro",
     "uses"
    ]
   },
   "metaRaw": {
    "type": "string"
   },
   "name": {
    "type": "string"
   },
   "reactions": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "description": {
       "type": "string"
      },
      "md": {
       "type": "string"
      },
      "name": {
       "type": "string"
      },
      "page": {
       "type": "integer"
      },
      "uses": {
       "type": "string",
       "enum": [
        "1/día",
        "2/día",
        "3/día",
        "recarga 5–6"
       ]
      }
     },
     "required": [
      "description",
      "md",
      "name",
      "page"
     ]
    }
   },
   "refs": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "resistances": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "senses": {
    "type": "object",
    "properties": {
     "passivePerception": {
      "type": "integer"
     },
     "raw": {
      "type": "string"
     }
    },
    "required": [
     "passivePerception",
     "raw"
    ]
   },
   "size": {
    "type": "string",
    "enum": [
     "Diminuto",
     "Enorme",
     "Gargantuesco",
     "Grande",
     "Mediano",
     "Pequeño"
    ]
   },
   "skills": {
    "type": "object",
    "properties": {
     "Acrobacias": {
      "type": "integer"
     },
     "Atletismo": {
      "type": "integer"
     },
     "Conocimiento arcano": {
      "type": "integer"
     },
     "Engaño": {
      "type": "integer"
     },
     "Historia": {
      "type": "integer"
     },
     "Interpretación": {
      "type": "integer"
     },
     "Investigación": {
      "type": "integer"
     },
     "Juego de manos": {
      "type": "integer"
     },
     "Medicina": {
      "type": "integer"
     },
     "Naturaleza": {
      "type": "integer"
     },
     "Percepción": {
      "type": "integer"
     },
     "Perspicacia": {
      "type": "integer"
     },
     "Persuasión": {
      "type": "integer"
     },
     "Religión": {
      "type": "integer"
     },
     "Sigilo": {
      "type": "integer"
     },
     "Supervivencia": {
      "type": "integer"
     }
    }
   },
   "source": {
    "type": "object",
    "properties": {
     "book": {
      "type": "string",
      "enum": [
       "SRD 5.2.1 es"
      ]
     },
     "page": {
      "type": "integer"
     },
     "pages": {
      "type": "array",
      "items": {
       "type": "integer"
      }
     }
    },
    "required": [
     "book",
     "page"
    ]
   },
   "speeds": {
    "type": "object",
    "properties": {
     "caminando": {
      "type": "number"
     },
     "excavar": {
      "type": "number"
     },
     "nadar": {
      "type": "number"
     },
     "trepar": {
      "type": "number"
     },
     "trepar o volar": {
      "type": "number"
     },
     "volar": {
      "type": "number"
     }
    },
    "required": [
     "caminando"
    ]
   },
   "tags": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "traits": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "description": {
       "type": "string"
      },
      "md": {
       "type": "string"
      },
      "name": {
       "type": [
        "string",
        "null"
       ]
      },
      "page": {
       "type": "integer"
      },
      "uses": {
       "type": "string",
       "enum": [
        "3/día",
        "3/día o 4/día en la guarida",
        "4/día",
        "4/día o 5/día en la guarida",
        "6/día"
       ]
      }
     },
     "required": [
      "md",
      "name",
      "page"
     ]
    }
   },
   "type": {
    "type": "string"
   },
   "vulnerabilities": {
    "type": "array",
    "items": {
     "type": "string",
     "enum": [
      "contundente",
      "daño perforante de armas empuñadas por criaturas bajo el efecto de un conjuro bendición",
      "frío",
      "fuego",
      "radiante",
      "trueno"
     ]
    }
   }
  },
  "required": [
   "abilities",
   "ac",
   "acRaw",
   "alignment",
   "challenge",
   "context",
   "hp",
   "id",
   "languages",
   "metaRaw",
   "name",
   "senses",
   "size",
   "source",
   "speeds",
   "type"
  ]
 }
}

=== gonzalorf/dnd-srd/data/processed/es/collections/monsters/cria-de-dragon-rojo.json
{
 "id": "monster.cria-de-dragon-rojo",
 "name": "Cría de dragón rojo",
 "source": {
  "book": "SRD 5.2.1 es",
  "page": 313
 },
 "context": [
  "Dragones rojos"
 ],
 "metaRaw": "Dragón Mediano (cromático), caótico malvado",
 "type": "Dragón",
 "alignment": "caótico malvado",
 "size": "Mediano",
 "tags": [
  "cromático"
 ],
 "ac": 17,
 "acRaw": "17",
 "initiative": {
  "mod": 2,
  "score": 12
 },
 "hp": {
  "raw": "75 (10d8 + 30)",
  "average": 75,
  "formula": "10d8 + 30"
 },
 "speeds": {
  "caminando": 9.0,
  "trepar": 9.0,
  "volar": 18.0
 },
 "skills": {
  "Percepción": 4,
  "Sigilo": 2
 },
 "senses": {
  "raw": "visión ciega 3 m, visión en la oscuridad 18 m; Percepción pasiva 14",
  "passivePerception": 14
 },
 "languages": [
  "dracónico"
 ],
 "immunities": [
  "fuego"
 ],
 "challenge": {
  "raw": "4 (1100 PX; BC +2)",
  "cr": 4,
  "xp": 1100,
  "proficiencyBonus": 2
 },
 "abilities": {
  "fue": {
   "score": 19,
   "mod": 4,
   "save": 4
  },
  "des": {
   "score": 10,
   "mod": 0,
   "save": 2
  },
  "con": {
   "score": 17,
   "mod": 3,
   "save": 3
  },
  "int": {
   "score": 12,
   "mod": 1,
   "save": 1
  },
  "sab": {
   "score": 11,
   "mod": 0,
   "save": 2
  },
  "car": {
   "score": 15,
   "mod": 2,
   "save": 2
  }
 },
 "actions": [
  {
   "name": "Ataque múltiple",
   "md": "***Ataque múltiple.*** El dragón realiza dos ataques de desgarro.",
   "page": 313,
   "description": "El dragón realiza dos ataques de desgarro."
  },
  {
   "name": "Desgarro",
   "md": "***Desgarro.*** *Tirada de ataque cuerpo a cuerpo:* +6, alcance 1,5 m. *Acierto:* 9 (1d10 + 4) de daño cortante más 3 (1d6) de daño de fuego.",
   "page": 313,
   "description": "*Tirada de ataque cuerpo a cuerpo:* +6, alcance 1,5 m. *Acierto:* 9 (1d10 + 4) de daño cortante más 3 (1d6) de daño de fuego."
  },
  {
   "name": "Aliento de fuego",
   "md": "***Aliento de fuego (recarga 5–6).*** *Tirada de salvación de Destreza:* CD 13, todas las criaturas en un cono de 4,5 m. *Fallo:* 24 (7d6) de daño de fuego. *Éxito:* la mitad del daño.",
   "page": 313,
   "description": "*Tirada de salvación de Destreza:* CD 13, todas las criaturas en un cono de 4,5 m. *Fallo:* 24 (7d6) de daño de fuego. *Éxito:* la mitad del daño.",
   "uses": "recarga 5–6"
  }
 ]
}

=== gonzalorf/dnd-srd/data/processed/es/collections/monsters/dragon-azul-joven.json
{
 "id": "monster.dragon-azul-joven",
 "name": "Dragón azul joven",
 "source": {
  "book": "SRD 5.2.1 es",
  "page": 298
 },
 "context": [
  "Dragones azules"
 ],
 "metaRaw": "Dragón Grande (cromático), legal malvado",
 "type": "Dragón",
 "alignment": "legal malvado",
 "size": "Grande",
 "tags": [
  "cromático"
 ],
 "ac": 18,
 "acRaw": "18",
 "initiative": {
  "mod": 4,
  "score": 14
 },
 "hp": {
  "raw": "152 (16d10 + 64)",
  "average": 152,
  "formula": "16d10 + 64"
 },
 "speeds": {
  "caminando": 12.0,
  "excavar": 6.0,
  "volar": 24.0
 },
 "skills": {
  "Percepción": 9,
  "Sigilo": 4
 },
 "senses": {
  "raw": "visión ciega 9 m, visión en la oscuridad 36 m; Percepción pasiva 19",
  "passivePerception": 19
 },
 "languages": [
  "común",
  "dracónico"
 ],
 "immunities": [
  "relámpago"
 ],
 "challenge": {
  "raw": "9 (5000 PX; BC +4)",
  "cr": 9,
  "xp": 5000,
  "proficiencyBonus": 4
 },
 "abilities": {
  "fue": {
   "score": 21,
   "mod": 5,
   "save": 5
  },
  "des": {
   "score": 10,
   "mod": 0,
   "save": 4
  },
  "con": {
   "score": 19,
   "mod": 4,
   "save": 4
  },
  "int": {
   "score": 14,
   "mod": 2,
   "save": 2
  },
  "sab": {
   "score": 13,
   "mod": 1,
   "save": 5
  },
  "car": {
   "score": 17,
   "mod": 3,
   "save": 3
  }
 },
 "actions": [
  {
   "name": "Ataque múltiple",
   "md": "***Ataque múltiple.*** El dragón realiza tres ataques de desgarro.",
   "page": 298,
   "description": "El dragón realiza tres ataques de desgarro."
  },
  {
   "name": "Desgarro",
   "md": "***Desgarro.*** *Tirada de ataque cuerpo a cuerpo:* +9, alcance 3 m. *Acierto:* 12 (2d6 + 5) de daño cortante más 5 (1d10) de daño de relámpago.",
   "page": 298,
   "description": "*Tirada de ataque cuerpo a cuerpo:* +9, alcance 3 m. *Acierto:* 12 (2d6 + 5) de daño cortante más 5 (1d10) de daño de relámpago."
  },
  {
   "name": "Aliento de relámpago",
   "md": "***Aliento de relámpago (recarga 5–6).*** *Tirada de salvación de Destreza:* CD 16, todas las criaturas en una línea de 18 m de largo y 1,5 m de ancho. *Fallo:*",
   "page": 298,
   "description": "*Tirada de salvación de Destreza:* CD 16, todas las criaturas en una línea de 18 m de largo y 1,5 m de ancho. *Fallo:*",
   "uses": "recarga 5–6"
  },
  {
   "name": null,
   "md": "55 (10d10) de daño de relámpago. *Éxito:* la mitad del daño.",
   "page": 298
  }
 ]
}

=== gonzalorf/dnd-srd/data/processed/es/collections/monsters/zombi.json
{
 "id": "monster.zombi",
 "name": "Zombi",
 "source": {
  "book": "SRD 5.2.1 es",
  "page": 376
 },
 "context": [
  "Zombis"
 ],
 "metaRaw": "Muerto viviente Mediano, neutral malvado",
 "type": "Muerto viviente",
 "alignment": "neutral malvado",
 "size": "Mediano",
 "ac": 8,
 "acRaw": "8",
 "initiative": {
  "mod": -2,
  "score": 8
 },
 "hp": {
  "raw": "15 (2d8 + 6)",
  "average": 15,
  "formula": "2d8 + 6"
 },
 "speeds": {
  "caminando": 6.0
 },
 "senses": {
  "raw": "visión en la oscuridad 18 m; Percepción pasiva 8",
  "passivePerception": 8
 },
 "languages": [
  "entiende común y otro idioma",
  "pero no puede hablar"
 ],
 "immunities": [
  "veneno",
  "cansancio",
  "envenenado"
 ],
 "challenge": {
  "raw": "1/4 (50 PX; BC +2)",
  "cr": 0.25,
  "xp": 50,
  "proficiencyBonus": 2
 },
 "abilities": {
  "fue": {
   "score": 13,
   "mod": 1,
   "save": 1
  },
  "des": {
   "score": 6,
   "mod": -2,
   "save": -2
  },
  "con": {
   "score": 16,
   "mod": 3,
   "save": 3
  },
  "int": {
   "score": 3,
   "mod": -4,
   "save": -4
  },
  "sab": {
   "score": 6,
   "mod": -2,
   "save": 0
  },
  "car": {
   "score": 5,
   "mod": -3,
   "save": -3
  }
 },
 "traits": [
  {
   "name": "Fortaleza de muerto viviente",
   "md": "***Fortaleza de muerto viviente.*** Si el daño reduce a 0 los puntos de golpe del zombi, hará una tirada de salvación de Constitución (CD 5 más el daño sufrido), siempre que el daño no sea radiante o proceda de un crítico. Si la supera, el zombi se queda con 1 punto de golpe.",
   "page": 376,
   "description": "Si el daño reduce a 0 los puntos de golpe del zombi, hará una tirada de salvación de Constitución (CD 5 más el daño sufrido), siempre que el daño no sea radiante o proceda de un crítico. Si la supera, el zombi se queda con 1 punto de golpe."
  }
 ],
 "actions": [
  {
   "name": "Golpe",
   "md": "***Golpe.*** *Tirada de ataque cuerpo a cuerpo:* +3, alcance 1,5 m. *Acierto:* 5 (1d8 + 1) de daño contundente.",
   "page": 376,
   "description": "*Tirada de ataque cuerpo a cuerpo:* +3, alcance 1,5 m. *Acierto:* 5 (1d8 + 1) de daño contundente."
  }
 ]
}

=== gonzalorf/dnd-srd/data/processed/es/collections/monsters/dragon-de-oropel-anciano.json
{
 "id": "monster.dragon-de-oropel-anciano",
 "name": "Dragón de oropel anciano",
 "source": {
  "book": "SRD 5.2.1 es",
  "page": 308,
  "pages": [
   308,
   309
  ]
 },
 "context": [
  "Dragones de oropel"
 ],
 "metaRaw": "Dragón Gargantuesco (metálico), caótico bueno",
 "type": "Dragón",
 "alignment": "caótico bueno",
 "size": "Gargantuesco",
 "tags": [
  "metálico"
 ],
 "ac": 20,
 "acRaw": "20",
 "initiative": {
  "mod": 12,
  "score": 22
 },
 "hp": {
  "raw": "332 (19d20 + 133)",
  "average": 332,
  "formula": "19d20 + 133"
 },
 "speeds": {
  "caminando": 12.0,
  "excavar": 12.0,
  "volar": 24.0
 },
 "skills": {
  "Historia": 9,
  "Percepción": 14,
  "Persuasión": 12,
  "Sigilo": 6
 },
 "senses": {
  "raw": "visión ciega 18 m, visión en la oscuridad 36 m; Percepción pasiva 24",
  "passivePerception": 24
 },
 "languages": [
  "común",
  "dracónico"
 ],
 "immunities": [
  "fuego"
 ],
 "challenge": {
  "raw": "20 (25 000 PX o 33 000 en la guarida; BC +6)",
  "cr": 20,
  "xp": 25000,
  "proficiencyBonus": 6,
  "xpInLair": 33000
 },
 "abilities": {
  "fue": {
   "score": 27,
   "mod": 8,
   "save": 8
  },
  "des": {
   "score": 10,
   "mod": 0,
   "save": 6
  },
  "con": {
   "score": 25,
   "mod": 7,
   "save": 7
  },
  "int": {
   "score": 16,
   "mod": 3,
   "save": 3
  },
  "sab": {
   "score": 15,
   "mod": 2,
   "save": 8
  },
  "car": {
   "score": 22,
   "mod": 6,
   "save": 6
  }
 },
 "traits": [
  {
   "name": "Resistencia legendaria",
   "md": "***Resistencia legendaria (4/día o 5/día en la guarida).*** El dragón puede elegir tener éxito en una tirada de salvación que haya fallado.",
   "page": 308,
   "description": "El dragón puede elegir tener éxito en una tirada de salvación que haya fallado.",
   "uses": "4/día o 5/día en la guarida"
  }
 ],
 "actions": [
  {
   "name": "Ataque múltiple",
   "md": "***Ataque múltiple.*** El dragón realiza tres ataques de desgarro. Puede sustituir un ataque por un uso de (A) su aliento somnífero o de (B) su lanzamiento de conjuros para lanzar *rayo abrasador* (versión de nivel 3).",
   "page": 308,
   "description": "El dragón realiza tres ataques de desgarro. Puede sustituir un ataque por un uso de (A) su aliento somnífero o de (B) su lanzamiento de conjuros para lanzar *rayo abrasador* (versión de nivel 3)."
  },
  {
   "name": "Desgarro",
   "md": "***Desgarro.*** *Tirada de ataque cuerpo a cuerpo:* +14, alcance 4,5 m. *Acierto:* 19 (2d10 + 8) de daño cortante más 7 (2d6) de daño de fuego.",
   "page": 309,
   "description": "*Tirada de ataque cuerpo a cuerpo:* +14, alcance 4,5 m. *Acierto:* 19 (2d10 + 8) de daño cortante más 7 (2d6) de daño de fuego."
  },
  {
   "name": "Aliento de fuego",
   "md": "***Aliento de fuego (recarga 5–6)***. *Tirada de salvación de Destreza:* CD 21, todas las criaturas en una línea de 27 m de largo y 1,5 m de ancho. *Fallo:* 58 (13d8) de daño de fuego. *Éxito:* la mitad del daño.",
   "page": 309,
   "description": ". *Tirada de salvación de Destreza:* CD 21, todas las criaturas en una línea de 27 m de largo y 1,5 m de ancho. *Fallo:* 58 (13d8) de daño de fuego. *Éxito:* la mitad del daño.",
   "uses": "recarga 5–6"
  },
  {
   "name": "Aliento somnífero",
   "md": "***Aliento somnífero.*** *Tirada de salvación de Constitución:* CD 21, todas las criaturas en un cono de 27 m. *Fallo:* el objetivo tendrá el estado de incapacitado hasta el final de su siguiente turno, momento en el que repetirá la tirada de salvación. *Segundo fallo:* el objetivo tendrá el estado de inconsciente durante 10 minutos. Este efecto acabará si el objetivo sufre daño o si una criatura que se encuentre a 1,5 m o menos de él lleva a cabo una acción para despertarlo.",
   "page": 309,
   "description": "*Tirada de salvación de Constitución:* CD 21, todas las criaturas en un cono de 27 m. *Fallo:* el objetivo tendrá el estado de incapacitado hasta el final de su siguiente turno, momento en el que repetirá la tirada de salvación. *Segundo fallo:* el objetivo tendrá el estado de inconsciente durante 10 minutos. Este efecto acabará si el objetivo sufre daño o si una criatura que se encuentre a 1,5 m o menos de él lleva a cabo una acción para despertarlo."
  },
  {
   "name": "Lanzamiento de conjuros",
   "md": "***Lanzamiento de conjuros.*** El dragón lanza uno de los siguientes conjuros, que no requiere componentes materiales y utiliza el Carisma como aptitud mágica (CD de salvación de conjuros 20):",
   "page": 309,
   "description": "El dragón lanza uno de los siguientes conjuros, que no requiere componentes materiales y utiliza el Carisma como aptitud mágica (CD de salvación de conjuros 20):"
  },
  {
   "name": null,
   "md": "A voluntad: *cambiar de forma* (solo forma de bestia o humanoide, no se obtienen puntos de golpe temporales del conjuro y no se requieren concentración ni puntos de golpe temporales para mantener el conjuro), *detectar magia*, *hablar con los animales*, *ilusión menor*, *rayo abrasador* (versión de nivel 3) 1/día cada uno: *controlar el clima*, *detectar pensamientos*",
   "page": 309
  }
 ],
 "legendary": {
  "actions": [
   {
    "name": "Abalanzarse",
    "md": "***Abalanzarse.*** El dragón se mueve hasta la mitad de su velocidad y realiza un ataque de desgarro.",
    "page": 309,
    "description": "El dragón se mueve hasta la mitad de su velocidad y realiza un ataque de desgarro."
   },
   {
    "name": "Arena abrasante",
    "md": "***Arena abrasante.*** *Tirada de salvación de Destreza:* CD 20, una criatura que el dragón pueda ver a 36 m o menos. *Fallo:* 36 (8d8) de daño de fuego y la velocidad del objetivo se reducirá a la mitad hasta el final de su siguiente turno. *Fallo o éxito:* el dragón no puede volver a realizar esta acción hasta el principio de su siguiente turno.",
    "page": 309,
    "description": "*Tirada de salvación de Destreza:* CD 20, una criatura que el dragón pueda ver a 36 m o menos. *Fallo:* 36 (8d8) de daño de fuego y la velocidad del objetivo se reducirá a la mitad hasta el final de su siguiente turno. *Fallo o éxito:* el dragón no puede volver a realizar esta acción hasta el principio de su siguiente turno."
   },
   {
    "name": "Luz calcinadora",
    "md": "***Luz calcinadora.*** El dragón utiliza su lanzamiento de conjuros para lanzar *rayo abrasador* (versión de nivel 3).",
    "page": 309,
    "description": "El dragón utiliza su lanzamiento de conjuros para lanzar *rayo abrasador* (versión de nivel 3)."
   }
  ],
  "intro": "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, el dragón puede emplear un uso para llevar a cabo una de las siguientes acciones. El dragón recupera todos los usos al principio de cada uno de sus turnos.",
  "uses": 3,
  "usesInLair": 4
 },
 "refs": [
  "spell.rayo-abrasador",
  "spell.cambiar-de-forma",
  "spell.detectar-magia",
  "spell.hablar-con-los-animales",
  "spell.ilusion-menor",
  "spell.controlar-el-clima",
  "spell.detectar-pensamientos"
 ]
}
