=== gonzalorf/dnd-srd/schemas/es/monsters.schema.json
{
 "$schema": "https://json-schema.org/draft/2020-12/schema",
 "title": "monsters",
 "description": "Inferido de 336 fichas de la colección «monsters».",
 "type": "array",
 "items": {
  "type": "object",
  "properties": {
   "abilities": {
    "type": "object",
    "properties": {
     "car": {
      "type": "object",
      "properties": {
       "mod": {
        "type": "integer"
       },
       "save": {
        "type": "integer"
       },
       "score": {
        "type": "integer"
       }
      },
      "required": [
       "mod",
       "save",
       "score"
      ]
     },
     "con": {
      "type": "object",
      "properties": {
       "mod": {
        "type": "integer"
       },
       "save": {
        "type": "integer"
       },
       "score": {
        "type": "integer"
       }
      },
      "required": [
       "mod",
       "save",
       "score"
      ]
     },
     "des": {
      "type": "object",
      "properties": {
       "mod": {
        "type": "integer"
       },
       "save": {
        "type": "integer"
       },
       "score": {
        "type": "integer"
       }
      },
      "required": [
       "mod",
       "save",
       "score"
      ]
     },
     "fue": {
      "type": "object",
      "properties": {
       "mod": {
        "type": "integer"
       },
       "save": {
        "type": "integer"
       },
       "score": {
        "type": "integer"
       }
      },
      "required": [
       "mod",
       "save",
       "score"
      ]
     },
     "int": {
      "type": "object",
      "properties": {
       "mod": {
        "type": "integer"
       },
       "save": {
        "type": "integer"
       },
       "score": {
        "type": "integer"
       }
      },
      "required": [
       "mod",
       "save",
       "score"
      ]
     },
     "sab": {
      "type": "object",
      "properties": {
       "mod": {
        "type": "integer"
       },
       "save": {
        "type": "integer"
       },
       "score": {
        "type": "integer"
       }
      },
      "required": [
       "mod",
       "save",
       "score"
      ]
     }
    },
    "required": [
     "car",
     "con",
     "des",
     "fue",
     "int",
     "sab"
    ]
   },
   "ac": {
    "type": "integer"
   },
   "acRaw": {
    "type": "string"
   },
   "actions": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "description": {
       "type": "string"
      },
      "md": {
       "type": "string"
      },
      "name": {
       "type": [
        "string",
        "null"
       ]
      },
      "page": {
       "type": "integer"
      },
      "uses": {
       "type": "string",
       "enum": [
        "1/día",
        "2/día",
        "3/día",
        "recarga 4–6",
        "recarga 5–6",
        "recarga 6"
       ]
      }
     },
     "required": [
      "md",
      "name",
      "page"
     ]
    }
   },
   "alignment": {
    "type": "string"
   },
   "bonusActions": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "description": {
       "type": "string"
      },
      "md": {
       "type": "string"
      },
      "name": {
       "type": [
        "string",
        "null"
       ]
      },
      "page": {
       "type": "integer"
      },
      "uses": {
       "type": "string",
       "enum": [
        "1/día",
        "2/día",
        "3/día",
        "recarga 4–6",
        "recarga 5–6",
        "recarga 6",
        "se recarga tras un descanso corto o largo",
        "solo celestial; se recarga tras un descanso largo",
        "solo feérico; se recarga tras un descanso largo",
        "solo infernal; se recarga tras un descanso largo"
       ]
      }
     },
     "required": [
      "md",
      "name",
      "page"
     ]
    }
   },
   "challenge": {
    "type": "object",
    "properties": {
     "cr": {
      "type": "number"
     },
     "proficiencyBonus": {
      "type": "integer"
     },
     "raw": {
      "type": "string"
     },
     "xp": {
      "type": "integer"
     },
     "xpInLair": {
      "type": "integer"
     }
    },
    "required": [
     "raw"
    ]
   },
   "context": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "gear": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "hp": {
    "type": "object",
    "properties": {
     "average": {
      "type": "integer"
     },
     "formula": {
      "type": "string"
     },
     "raw": {
      "type": "string"
     }
    },
    "required": [
     "raw"
    ]
   },
   "id": {
    "type": "string"
   },
   "immunities": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "initiative": {
    "type": "object",
    "properties": {
     "mod": {
      "type": "integer"
     },
     "score": {
      "type": "integer"
     }
    },
    "required": [
     "mod",
     "score"
    ]
   },
   "languages": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "legendary": {
    "type": "object",
    "properties": {
     "actions": {
      "type": "array",
      "items": {
       "type": "object",
       "properties": {
        "description": {
         "type": "string"
        },
        "md": {
         "type": "string"
        },
        "name": {
         "type": [
          "string",
          "null"
         ]
        },
        "page": {
         "type": "integer"
        }
       },
       "required": [
        "md",
        "name",
        "page"
       ]
      }
     },
     "intro": {
      "type": "string",
      "enum": [
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, el aboleth puede emplear un uso para llevar a cabo una de las siguientes acciones. El aboleth recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, el dragón puede emplear un uso para llevar a cabo una de las siguientes acciones. El dragón recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, el kraken puede emplear un uso para llevar a cabo una de las siguientes acciones. El kraken recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, el liche puede emplear un uso para llevar a cabo una de las siguientes acciones. El liche recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, el vampiro puede emplear un uso para llevar a cabo una de las siguientes acciones. El vampiro recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, la esfinge puede emplear un uso para llevar a cabo una de las siguientes acciones. La esfinge recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, la momia puede emplear un uso para llevar a cabo una de las siguientes acciones. La momia recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3. Justo después del turno de otra criatura, el solar puede emplear un uso para llevar a cabo una de las siguientes acciones. El solar recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3. Justo después del turno de otra criatura, el unicornio puede emplear un uso para llevar a cabo una de las siguientes acciones. El unicornio recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3. Justo después del turno de otra criatura, la tarasca puede emplear un uso para llevar a cabo una de las siguientes acciones. La tarasca recupera todos los usos al principio de cada uno de sus turnos."
      ]
     },
     "uses": {
      "type": "integer"
     },
     "usesInLair": {
      "type": "integer"
     }
    },
    "required": [
     "actions",
     "intro",
     "uses"
    ]
   },
   "metaRaw": {
    "type": "string"
   },
   "name": {
    "type": "string"
   },
   "reactions": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "description": {
       "type": "string"
      },
      "md": {
       "type": "string"
      },
      "name": {
       "type": "string"
      },
      "page": {
       "type": "integer"
      },
      "uses": {
       "type": "string",
       "enum": [
        "1/día",
        "2/día",
        "3/día",
        "recarga 5–6"
       ]
      }
     },
     "required": [
      "description",
      "md",
      "name",
      "page"
     ]
    }
   },
   "refs": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "resistances": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "senses": {
    "type": "object",
    "properties": {
     "passivePerception": {
      "type": "integer"
     },
     "raw": {
      "type": "string"
     }
    },
    "required": [
     "passivePerception",
     "raw"
    ]
   },
   "size": {
    "type": "string",
    "enum": [
     "Diminuto",
     "Enorme",
     "Gargantuesco",
     "Grande",
     "Mediano",
     "Pequeño"
    ]
   },
   "skills": {
    "type": "object",
    "properties": {
     "Acrobacias": {
      "type": "integer"
     },
     "Atletismo": {
      "type": "integer"
     },
     "Conocimiento arcano": {
      "type": "integer"
     },
     "Engaño": {
      "type": "integer"
     },
     "Historia": {
      "type": "integer"
     },
     "Interpretación": {
      "type": "integer"
     },
     "Investigación": {
      "type": "integer"
     },
     "Juego de manos": {
      "type": "integer"
     },
     "Medicina": {
      "type": "integer"
     },
     "Naturaleza": {
      "type": "integer"
     },
     "Percepción": {
      "type": "integer"
     },
     "Perspicacia": {
      "type": "integer"
     },
     "Persuasión": {
      "type": "integer"
     },
     "Religión": {
      "type": "integer"
     },
     "Sigilo": {
      "type": "integer"
     },
     "Supervivencia": {
      "type": "integer"
     }
    }
   },
   "source": {
    "type": "object",
    "properties": {
     "book": {
      "type": "string",
      "enum": [
       "SRD 5.2.1 es"
      ]
     },
     "page": {
      "type": "integer"
     },
     "pages": {
      "type": "array",
      "items": {
       "type": "integer"
      }
     }
    },
    "required": [
     "book",
     "page"
    ]
   },
   "speeds": {
    "type": "object",
    "properties": {
     "caminando": {
      "type": "number"
     },
     "excavar": {
      "type": "number"
     },
     "nadar": {
      "type": "number"
     },
     "trepar": {
      "type": "number"
     },
     "trepar o volar": {
      "type": "number"
     },
     "volar": {
      "type": "number"
     }
    },
    "required": [
     "caminando"
    ]
   },
   "tags": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "traits": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "description": {
       "type": "string"
      },
      "md": {
       "type": "string"
      },
      "name": {
       "type": [
        "string",
        "null"
       ]
      },
      "page": {
       "type": "integer"
      },
      "uses": {
       "type": "string",
       "enum": [
        "3/día",
        "3/día o 4/día en la guarida",
        "4/día",
        "4/día o 5/día en la guarida",
        "6/día"
       ]
      }
     },
     "required": [
      "md",
      "name",
      "page"
     ]
    }
   },
   "type": {
    "type": "string"
   },
   "vulnerabilities": {
    "type": "array",
    "items": {
     "type": "string",
     "enum": [
      "contundente",
      "daño perforante de armas empuñadas por criaturas bajo el efecto de un conjuro bendición",
      "frío",
      "fuego",
      "radiante",
      "trueno"
     ]
    }
   }
  },
  "required": [
   "abilities",
   "ac",
   "acRaw",
   "alignment",
   "challenge",
   "context",
   "hp",
   "id",
   "languages",
   "metaRaw",
   "name",
   "senses",
   "size",
   "source",
   "speeds",
   "type"
  ]
 }
}

=== gonzalorf/dnd-srd/data/processed/es/collections/monsters/dragon-verde-anciano.json
{
 "id": "monster.dragon-verde-anciano",
 "name": "Dragón verde anciano",
 "source": {
  "book": "SRD 5.2.1 es",
  "page": 316
 },
 "context": [
  "Dragones verdes"
 ],
 "metaRaw": "Dragón Gargantuesco (cromático), legal malvado",
 "type": "Dragón",
 "alignment": "legal malvado",
 "size": "Gargantuesco",
 "tags": [
  "cromático"
 ],
 "ac": 21,
 "acRaw": "21",
 "initiative": {
  "mod": 15,
  "score": 25
 },
 "hp": {
  "raw": "402 (23d20 + 161)",
  "average": 402,
  "formula": "23d20 + 161"
 },
 "speeds": {
  "caminando": 12.0,
  "nadar": 12.0,
  "volar": 24.0
 },
 "skills": {
  "Engaño": 13,
  "Percepción": 17,
  "Persuasión": 13,
  "Sigilo": 8
 },
 "senses": {
  "raw": "visión ciega 18 m, visión en la oscuridad 36 m; Percepción pasiva 27",
  "passivePerception": 27
 },
 "languages": [
  "común",
  "dracónico"
 ],
 "immunities": [
  "veneno",
  "envenenado"
 ],
 "challenge": {
  "raw": "22 (41 000 PX o 50 000 en la guarida; BC +7)",
  "cr": 22,
  "xp": 41000,
  "proficiencyBonus": 7,
  "xpInLair": 50000
 },
 "abilities": {
  "fue": {
   "score": 27,
   "mod": 8,
   "save": 8
  },
  "des": {
   "score": 12,
   "mod": 1,
   "save": 8
  },
  "con": {
   "score": 25,
   "mod": 7,
   "save": 7
  },
  "int": {
   "score": 20,
   "mod": 5,
   "save": 5
  },
  "sab": {
   "score": 17,
   "mod": 3,
   "save": 10
  },
  "car": {
   "score": 22,
   "mod": 6,
   "save": 6
  }
 },
 "traits": [
  {
   "name": "Anfibio",
   "md": "***Anfibio.*** El dragón puede respirar tanto dentro como fuera del agua.",
   "page": 316,
   "description": "El dragón puede respirar tanto dentro como fuera del agua."
  },
  {
   "name": "Resistencia legendaria",
   "md": "***Resistencia legendaria (4/día o 5/día en la guarida).*** El dragón puede elegir tener éxito en una tirada de salvación que haya fallado.",
   "page": 316,
   "description": "El dragón puede elegir tener éxito en una tirada de salvación que haya fallado.",
   "uses": "4/día o 5/día en la guarida"
  }
 ],
 "actions": [
  {
   "name": "Ataque múltiple",
   "md": "***Ataque múltiple.*** El dragón realiza tres ataques de desgarro. Puede sustituir un ataque por un uso de su lanzamiento de conjuros para lanzar *clavo mental* (versión de nivel 5).",
   "page": 316,
   "description": "El dragón realiza tres ataques de desgarro. Puede sustituir un ataque por un uso de su lanzamiento de conjuros para lanzar *clavo mental* (versión de nivel 5)."
  },
  {
   "name": "Desgarro",
   "md": "***Desgarro.*** *Tirada de ataque cuerpo a cuerpo:* +15, alcance 4,5 m. *Acierto:* 17 (2d8 + 8) de daño cortante más 10 (3d6) de daño de veneno.",
   "page": 316,
   "description": "*Tirada de ataque cuerpo a cuerpo:* +15, alcance 4,5 m. *Acierto:* 17 (2d8 + 8) de daño cortante más 10 (3d6) de daño de veneno."
  },
  {
   "name": "Aliento venenoso",
   "md": "***Aliento venenoso (recarga 5–6).*** *Tirada de salvación de Constitución:* CD 22, todas las criaturas en un cono de 27 m. *Fallo:* 77 (22d6) de daño de veneno. *Éxito:* la mitad del daño.",
   "page": 316,
   "description": "*Tirada de salvación de Constitución:* CD 22, todas las criaturas en un cono de 27 m. *Fallo:* 77 (22d6) de daño de veneno. *Éxito:* la mitad del daño.",
   "uses": "recarga 5–6"
  },
  {
   "name": "Lanzamiento de conjuros",
   "md": "***Lanzamiento de conjuros.*** El dragón lanza uno de los siguientes conjuros, que no requiere componentes materiales y utiliza el Carisma como aptitud mágica (CD de salvación de conjuros 21):",
   "page": 316,
   "description": "El dragón lanza uno de los siguientes conjuros, que no requiere componentes materiales y utiliza el Carisma como aptitud mágica (CD de salvación de conjuros 21):"
  },
  {
   "name": null,
   "md": "A voluntad: *clavo mental* (versión de nivel 5), *detectar magia* 1/día cada uno: *alterar los recuerdos*, *geas*",
   "page": 316
  }
 ],
 "legendary": {
  "actions": [
   {
    "name": "Abalanzarse",
    "md": "***Abalanzarse.*** El dragón se mueve hasta la mitad de su velocidad y realiza un ataque de desgarro.",
    "page": 316,
    "description": "El dragón se mueve hasta la mitad de su velocidad y realiza un ataque de desgarro."
   },
   {
    "name": "Invasión mental",
    "md": "***Invasión mental.*** El dragón utiliza su lanzamiento de conjuros para lanzar *clavo mental* (versión de nivel 5).",
    "page": 316,
    "description": "El dragón utiliza su lanzamiento de conjuros para lanzar *clavo mental* (versión de nivel 5)."
   },
   {
    "name": "Miasma venenoso",
    "md": "***Miasma venenoso.*** *Tirada de salvación de Constitución:* CD 21, todas las criaturas en una esfera de 9 m de radio centrada en un punto que el dragón pueda ver a 27 m o menos. *Fallo:* 17 (5d6) de daño de veneno y el objetivo tendrá un penalizador de −2 a la CA hasta el final de su siguiente turno. *Fallo o éxito:* el dragón no puede volver a realizar esta acción hasta el principio de su siguiente turno.",
    "page": 316,
    "description": "*Tirada de salvación de Constitución:* CD 21, todas las criaturas en una esfera de 9 m de radio centrada en un punto que el dragón pueda ver a 27 m o menos. *Fallo:* 17 (5d6) de daño de veneno y el objetivo tendrá un penalizador de −2 a la CA hasta el final de su siguiente turno. *Fallo o éxito:* el dragón no puede volver a realizar esta acción hasta el principio de su siguiente turno."
   }
  ],
  "intro": "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, el dragón puede emplear un uso para llevar a cabo una de las siguientes acciones. El dragón recupera todos los usos al principio de cada uno de sus turnos.",
  "uses": 3,
  "usesInLair": 4
 },
 "refs": [
  "spell.clavo-mental",
  "spell.detectar-magia",
  "spell.alterar-los-recuerdos",
  "spell.geas"
 ]
}

=== gonzalorf/dnd-srd/data/processed/es/collections/monsters/dragon-de-cobre-anciano.json
{
 "id": "monster.dragon-de-cobre-anciano",
 "name": "Dragón de cobre anciano",
 "source": {
  "book": "SRD 5.2.1 es",
  "page": 304,
  "pages": [
   304,
   305
  ]
 },
 "context": [
  "Dragones de cobre"
 ],
 "metaRaw": "Dragón Gargantuesco (metálico), caótico bueno",
 "type": "Dragón",
 "alignment": "caótico bueno",
 "size": "Gargantuesco",
 "tags": [
  "metálico"
 ],
 "ac": 21,
 "acRaw": "21",
 "initiative": {
  "mod": 15,
  "score": 25
 },
 "hp": {
  "raw": "367 (21d20 + 147)",
  "average": 367,
  "formula": "21d20 + 147"
 },
 "speeds": {
  "caminando": 12.0,
  "trepar": 12.0,
  "volar": 24.0
 },
 "skills": {
  "Engaño": 13,
  "Percepción": 17,
  "Sigilo": 8
 },
 "senses": {
  "raw": "visión ciega 18 m, visión en la oscuridad 36 m; Percepción pasiva 27",
  "passivePerception": 27
 },
 "languages": [
  "común",
  "dracónico"
 ],
 "immunities": [
  "ácido"
 ],
 "challenge": {
  "raw": "21 (33 000 PX o 41 000 en la guarida; BC +7)",
  "cr": 21,
  "xp": 33000,
  "proficiencyBonus": 7,
  "xpInLair": 41000
 },
 "abilities": {
  "fue": {
   "score": 27,
   "mod": 8,
   "save": 8
  },
  "des": {
   "score": 12,
   "mod": 1,
   "save": 8
  },
  "con": {
   "score": 25,
   "mod": 7,
   "save": 7
  },
  "int": {
   "score": 20,
   "mod": 5,
   "save": 5
  },
  "sab": {
   "score": 17,
   "mod": 3,
   "save": 10
  },
  "car": {
   "score": 22,
   "mod": 6,
   "save": 6
  }
 },
 "traits": [
  {
   "name": "Resistencia legendaria",
   "md": "***Resistencia legendaria (4/día o 5/día en la guarida).*** El dragón puede elegir tener éxito en una tirada de salvación que haya fallado.",
   "page": 304,
   "description": "El dragón puede elegir tener éxito en una tirada de salvación que haya fallado.",
   "uses": "4/día o 5/día en la guarida"
  }
 ],
 "actions": [
  {
   "name": "Ataque múltiple",
   "md": "***Ataque múltiple.*** El dragón realiza tres ataques de desgarro. Puede sustituir un ataque por un uso de (A) su aliento ralentizador o de (B) su lanzamiento de conjuros para lanzar *clavo mental* (versión de nivel 5).",
   "page": 304,
   "description": "El dragón realiza tres ataques de desgarro. Puede sustituir un ataque por un uso de (A) su aliento ralentizador o de (B) su lanzamiento de conjuros para lanzar *clavo mental* (versión de nivel 5)."
  },
  {
   "name": "Desgarro",
   "md": "***Desgarro.*** *Tirada de ataque cuerpo a cuerpo:* +15, alcance 4,5 m. *Acierto:* 19 (2d10 + 8) de daño cortante más 9 (2d8) de daño de ácido.",
   "page": 304,
   "description": "*Tirada de ataque cuerpo a cuerpo:* +15, alcance 4,5 m. *Acierto:* 19 (2d10 + 8) de daño cortante más 9 (2d8) de daño de ácido."
  },
  {
   "name": "Aliento ácido",
   "md": "***Aliento ácido (recarga 5–6)***. *Tirada de salvación de Destreza:* CD 22, todas las criaturas en una línea de 27 m de largo y 3 m de ancho. *Fallo:* 63 (14d8) de daño de ácido. *Éxito:* la mitad del daño.",
   "page": 304,
   "description": ". *Tirada de salvación de Destreza:* CD 22, todas las criaturas en una línea de 27 m de largo y 3 m de ancho. *Fallo:* 63 (14d8) de daño de ácido. *Éxito:* la mitad del daño.",
   "uses": "recarga 5–6"
  },
  {
   "name": "Aliento ralentizador",
   "md": "***Aliento ralentizador.*** *Tirada de salvación de Constitución:* CD 22, todas las criaturas en un cono de 27 m. *Fallo:* el objetivo no podrá llevar a cabo reacciones, su velocidad se reducirá a la mitad y podrá realizar una acción o una acción adicional en su turno, pero no ambas. Este efecto durará hasta el final de su siguiente turno.",
   "page": 304,
   "description": "*Tirada de salvación de Constitución:* CD 22, todas las criaturas en un cono de 27 m. *Fallo:* el objetivo no podrá llevar a cabo reacciones, su velocidad se reducirá a la mitad y podrá realizar una acción o una acción adicional en su turno, pero no ambas. Este efecto durará hasta el final de su siguiente turno."
  },
  {
   "name": "Lanzamiento de conjuros",
   "md": "***Lanzamiento de conjuros.*** El dragón lanza uno de los siguientes conjuros, que no requiere componentes ma",
   "page": 304,
   "description": "El dragón lanza uno de los siguientes conjuros, que no requiere componentes ma"
  },
  {
   "name": null,
   "md": "teriales y utiliza el Carisma como aptitud mágica (CD de salvación de conjuros 21):",
   "page": 305
  },
  {
   "name": null,
   "md": "A voluntad: *cambiar de forma* (solo forma de bestia o humanoide, no se obtienen puntos de golpe temporales del conjuro y no se requieren concentración ni puntos de golpe temporales para mantener el conjuro), *clavo mental* (versión de nivel 5), *detectar magia*, *ilusión menor* 1/día cada uno: *imagen mayor*, *proyectar imagen*, *restablecimiento mayor*",
   "page": 305
  }
 ],
 "legendary": {
  "actions": [
   {
    "name": "Abalanzarse",
    "md": "***Abalanzarse.*** El dragón se mueve hasta la mitad de su velocidad y realiza un ataque de desgarro.",
    "page": 305,
    "description": "El dragón se mueve hasta la mitad de su velocidad y realiza un ataque de desgarro."
   },
   {
    "name": "Magia de la risa",
    "md": "***Magia de la risa.*** *Tirada de salvación de Carisma:* CD 21, una criatura que el dragón pueda ver a 36 m o menos. *Fallo:* 31 (9d6) de daño psíquico. Hasta el final de su siguiente turno, el objetivo tirará 1d8 cada vez que haga una prueba de característica o tirada de ataque y restará el resultado a la prueba con d20. *Fallo o éxito:* el dragón no puede volver a realizar esta acción hasta el principio de su siguiente turno.",
    "page": 305,
    "description": "*Tirada de salvación de Carisma:* CD 21, una criatura que el dragón pueda ver a 36 m o menos. *Fallo:* 31 (9d6) de daño psíquico. Hasta el final de su siguiente turno, el objetivo tirará 1d8 cada vez que haga una prueba de característica o tirada de ataque y restará el resultado a la prueba con d20. *Fallo o éxito:* el dragón no puede volver a realizar esta acción hasta el principio de su siguiente turno."
   },
   {
    "name": "Sacudida mental",
    "md": "***Sacudida mental.*** El dragón utiliza su lanzamiento de conjuros para lanzar *clavo mental* (versión de nivel 5). El dragón no puede volver a realizar esta acción hasta el principio de su siguiente turno.",
    "page": 305,
    "description": "El dragón utiliza su lanzamiento de conjuros para lanzar *clavo mental* (versión de nivel 5). El dragón no puede volver a realizar esta acción hasta el principio de su siguiente turno."
   }
  ],
  "intro": "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, el dragón puede emplear un uso para llevar a cabo una de las siguientes acciones. El dragón recupera todos los usos al principio de cada uno de sus turnos.",
  "uses": 3,
  "usesInLair": 4
 },
 "refs": [
  "spell.clavo-mental",
  "spell.cambiar-de-forma",
  "spell.detectar-magia",
  "spell.ilusion-menor",
  "spell.imagen-mayor",
  "spell.proyectar-imagen",
  "spell.restablecimiento-mayor"
 ]
}

=== gonzalorf/dnd-srd/data/processed/es/collections/monsters/hongo-chillon.json
{
 "id": "monster.hongo-chillon",
 "name": "Hongo chillón",
 "source": {
  "book": "SRD 5.2.1 es",
  "page": 341
 },
 "context": [
  "Hongos"
 ],
 "metaRaw": "Planta Mediana, sin alineamiento",
 "type": "Planta",
 "alignment": "sin alineamiento",
 "size": "Mediano",
 "ac": 5,
 "acRaw": "5",
 "initiative": {
  "mod": -5,
  "score": 5
 },
 "hp": {
  "raw": "13 (3d8)",
  "average": 13,
  "formula": "3d8"
 },
 "speeds": {
  "caminando": 1.5
 },
 "senses": {
  "raw": "visión ciega 9 m; Percepción pasiva 6",
  "passivePerception": 6
 },
 "languages": [
  "ninguno"
 ],
 "immunities": [
  "asustado",
  "cegado",
  "ensordecido",
  "hechizado"
 ],
 "challenge": {
  "raw": "0 (0 PX; BC +2)",
  "cr": 0,
  "xp": 0,
  "proficiencyBonus": 2
 },
 "abilities": {
  "fue": {
   "score": 1,
   "mod": -5,
   "save": -5
  },
  "des": {
   "score": 1,
   "mod": -5,
   "save": -5
  },
  "con": {
   "score": 10,
   "mod": 0,
   "save": 0
  },
  "int": {
   "score": 1,
   "mod": -5,
   "save": -5
  },
  "sab": {
   "score": 3,
   "mod": -4,
   "save": -4
  },
  "car": {
   "score": 1,
   "mod": -5,
   "save": -5
  }
 },
 "reactions": [
  {
   "name": "Chillar",
   "md": "***Chillar.*** *Detonante:* una criatura o una fuente de luz brillante se acerca a 9 m o menos del chillón. *Respuesta:* el chillón emite un grito audible a 90 m de él durante 1 minuto o hasta que muera.",
   "page": 341,
   "description": "*Detonante:* una criatura o una fuente de luz brillante se acerca a 9 m o menos del chillón. *Respuesta:* el chillón emite un grito audible a 90 m de él durante 1 minuto o hasta que muera."
  }
 ]
}
