=== gonzalorf/dnd-srd/schemas/es/monsters.schema.json
{
 "$schema": "https://json-schema.org/draft/2020-12/schema",
 "title": "monsters",
 "description": "Inferido de 336 fichas de la colección «monsters».",
 "type": "array",
 "items": {
  "type": "object",
  "properties": {
   "abilities": {
    "type": "object",
    "properties": {
     "car": {
      "type": "object",
      "properties": {
       "mod": {
        "type": "integer"
       },
       "save": {
        "type": "integer"
       },
       "score": {
        "type": "integer"
       }
      },
      "required": [
       "mod",
       "save",
       "score"
      ]
     },
     "con": {
      "type": "object",
      "properties": {
       "mod": {
        "type": "integer"
       },
       "save": {
        "type": "integer"
       },
       "score": {
        "type": "integer"
       }
      },
      "required": [
       "mod",
       "save",
       "score"
      ]
     },
     "des": {
      "type": "object",
      "properties": {
       "mod": {
        "type": "integer"
       },
       "save": {
        "type": "integer"
       },
       "score": {
        "type": "integer"
       }
      },
      "required": [
       "mod",
       "save",
       "score"
      ]
     },
     "fue": {
      "type": "object",
      "properties": {
       "mod": {
        "type": "integer"
       },
       "save": {
        "type": "integer"
       },
       "score": {
        "type": "integer"
       }
      },
      "required": [
       "mod",
       "save",
       "score"
      ]
     },
     "int": {
      "type": "object",
      "properties": {
       "mod": {
        "type": "integer"
       },
       "save": {
        "type": "integer"
       },
       "score": {
        "type": "integer"
       }
      },
      "required": [
       "mod",
       "save",
       "score"
      ]
     },
     "sab": {
      "type": "object",
      "properties": {
       "mod": {
        "type": "integer"
       },
       "save": {
        "type": "integer"
       },
       "score": {
        "type": "integer"
       }
      },
      "required": [
       "mod",
       "save",
       "score"
      ]
     }
    },
    "required": [
     "car",
     "con",
     "des",
     "fue",
     "int",
     "sab"
    ]
   },
   "ac": {
    "type": "integer"
   },
   "acRaw": {
    "type": "string"
   },
   "actions": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "description": {
       "type": "string"
      },
      "md": {
       "type": "string"
      },
      "name": {
       "type": [
        "string",
        "null"
       ]
      },
      "page": {
       "type": "integer"
      },
      "uses": {
       "type": "string",
       "enum": [
        "1/día",
        "2/día",
        "3/día",
        "recarga 4–6",
        "recarga 5–6",
        "recarga 6"
       ]
      }
     },
     "required": [
      "md",
      "name",
      "page"
     ]
    }
   },
   "alignment": {
    "type": "string"
   },
   "bonusActions": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "description": {
       "type": "string"
      },
      "md": {
       "type": "string"
      },
      "name": {
       "type": [
        "string",
        "null"
       ]
      },
      "page": {
       "type": "integer"
      },
      "uses": {
       "type": "string",
       "enum": [
        "1/día",
        "2/día",
        "3/día",
        "recarga 4–6",
        "recarga 5–6",
        "recarga 6",
        "se recarga tras un descanso corto o largo",
        "solo celestial; se recarga tras un descanso largo",
        "solo feérico; se recarga tras un descanso largo",
        "solo infernal; se recarga tras un descanso largo"
       ]
      }
     },
     "required": [
      "md",
      "name",
      "page"
     ]
    }
   },
   "challenge": {
    "type": "object",
    "properties": {
     "cr": {
      "type": "number"
     },
     "proficiencyBonus": {
      "type": "integer"
     },
     "raw": {
      "type": "string"
     },
     "xp": {
      "type": "integer"
     },
     "xpInLair": {
      "type": "integer"
     }
    },
    "required": [
     "raw"
    ]
   },
   "context": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "gear": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "hp": {
    "type": "object",
    "properties": {
     "average": {
      "type": "integer"
     },
     "formula": {
      "type": "string"
     },
     "raw": {
      "type": "string"
     }
    },
    "required": [
     "raw"
    ]
   },
   "id": {
    "type": "string"
   },
   "immunities": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "initiative": {
    "type": "object",
    "properties": {
     "mod": {
      "type": "integer"
     },
     "score": {
      "type": "integer"
     }
    },
    "required": [
     "mod",
     "score"
    ]
   },
   "languages": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "legendary": {
    "type": "object",
    "properties": {
     "actions": {
      "type": "array",
      "items": {
       "type": "object",
       "properties": {
        "description": {
         "type": "string"
        },
        "md": {
         "type": "string"
        },
        "name": {
         "type": [
          "string",
          "null"
         ]
        },
        "page": {
         "type": "integer"
        }
       },
       "required": [
        "md",
        "name",
        "page"
       ]
      }
     },
     "intro": {
      "type": "string",
      "enum": [
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, el aboleth puede emplear un uso para llevar a cabo una de las siguientes acciones. El aboleth recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, el dragón puede emplear un uso para llevar a cabo una de las siguientes acciones. El dragón recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, el kraken puede emplear un uso para llevar a cabo una de las siguientes acciones. El kraken recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, el liche puede emplear un uso para llevar a cabo una de las siguientes acciones. El liche recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, el vampiro puede emplear un uso para llevar a cabo una de las siguientes acciones. El vampiro recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, la esfinge puede emplear un uso para llevar a cabo una de las siguientes acciones. La esfinge recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3 (4 en la guarida). Justo después del turno de otra criatura, la momia puede emplear un uso para llevar a cabo una de las siguientes acciones. La momia recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3. Justo después del turno de otra criatura, el solar puede emplear un uso para llevar a cabo una de las siguientes acciones. El solar recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3. Justo después del turno de otra criatura, el unicornio puede emplear un uso para llevar a cabo una de las siguientes acciones. El unicornio recupera todos los usos al principio de cada uno de sus turnos.",
       "Usos de acciones legendarias: 3. Justo después del turno de otra criatura, la tarasca puede emplear un uso para llevar a cabo una de las siguientes acciones. La tarasca recupera todos los usos al principio de cada uno de sus turnos."
      ]
     },
     "uses": {
      "type": "integer"
     },
     "usesInLair": {
      "type": "integer"
     }
    },
    "required": [
     "actions",
     "intro",
     "uses"
    ]
   },
   "metaRaw": {
    "type": "string"
   },
   "name": {
    "type": "string"
   },
   "reactions": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "description": {
       "type": "string"
      },
      "md": {
       "type": "string"
      },
      "name": {
       "type": "string"
      },
      "page": {
       "type": "integer"
      },
      "uses": {
       "type": "string",
       "enum": [
        "1/día",
        "2/día",
        "3/día",
        "recarga 5–6"
       ]
      }
     },
     "required": [
      "description",
      "md",
      "name",
      "page"
     ]
    }
   },
   "refs": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "resistances": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "senses": {
    "type": "object",
    "properties": {
     "passivePerception": {
      "type": "integer"
     },
     "raw": {
      "type": "string"
     }
    },
    "required": [
     "passivePerception",
     "raw"
    ]
   },
   "size": {
    "type": "string",
    "enum": [
     "Diminuto",
     "Enorme",
     "Gargantuesco",
     "Grande",
     "Mediano",
     "Pequeño"
    ]
   },
   "skills": {
    "type": "object",
    "properties": {
     "Acrobacias": {
      "type": "integer"
     },
     "Atletismo": {
      "type": "integer"
     },
     "Conocimiento arcano": {
      "type": "integer"
     },
     "Engaño": {
      "type": "integer"
     },
     "Historia": {
      "type": "integer"
     },
     "Interpretación": {
      "type": "integer"
     },
     "Investigación": {
      "type": "integer"
     },
     "Juego de manos": {
      "type": "integer"
     },
     "Medicina": {
      "type": "integer"
     },
     "Naturaleza": {
      "type": "integer"
     },
     "Percepción": {
      "type": "integer"
     },
     "Perspicacia": {
      "type": "integer"
     },
     "Persuasión": {
      "type": "integer"
     },
     "Religión": {
      "type": "integer"
     },
     "Sigilo": {
      "type": "integer"
     },
     "Supervivencia": {
      "type": "integer"
     }
    }
   },
   "source": {
    "type": "object",
    "properties": {
     "book": {
      "type": "string",
      "enum": [
       "SRD 5.2.1 es"
      ]
     },
     "page": {
      "type": "integer"
     },
     "pages": {
      "type": "array",
      "items": {
       "type": "integer"
      }
     }
    },
    "required": [
     "book",
     "page"
    ]
   },
   "speeds": {
    "type": "object",
    "properties": {
     "caminando": {
      "type": "number"
     },
     "excavar": {
      "type": "number"
     },
     "nadar": {
      "type": "number"
     },
     "trepar": {
      "type": "number"
     },
     "trepar o volar": {
      "type": "number"
     },
     "volar": {
      "type": "number"
     }
    },
    "required": [
     "caminando"
    ]
   },
   "tags": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "traits": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "description": {
       "type": "string"
      },
      "md": {
       "type": "string"
      },
      "name": {
       "type": [
        "string",
        "null"
       ]
      },
      "page": {
       "type": "integer"
      },
      "uses": {
       "type": "string",
       "enum": [
        "3/día",
        "3/día o 4/día en la guarida",
        "4/día",
        "4/día o 5/día en la guarida",
        "6/día"
       ]
      }
     },
     "required": [
      "md",
      "name",
      "page"
     ]
    }
   },
   "type": {
    "type": "string"
   },
   "vulnerabilities": {
    "type": "array",
    "items": {
     "type": "string",
     "enum": [
      "contundente",
      "daño perforante de armas empuñadas por criaturas bajo el efecto de un conjuro bendición",
      "frío",
      "fuego",
      "radiante",
      "trueno"
     ]
    }
   }
  },
  "required": [
   "abilities",
   "ac",
   "acRaw",
   "alignment",
   "challenge",
   "context",
   "hp",
   "id",
   "languages",
   "metaRaw",
   "name",
   "senses",
   "size",
   "source",
   "speeds",
   "type"
  ]
 }
}

=== gonzalorf/dnd-srd/data/processed/es/collections/monsters/manticora.json
{
 "id": "monster.manticora",
 "name": "Mantícora",
 "source": {
  "book": "SRD 5.2.1 es",
  "page": 347
 },
 "context": [
  "Mantícora"
 ],
 "metaRaw": "Monstruosidad Grande, legal malvada",
 "type": "Monstruosidad",
 "alignment": "legal malvada",
 "size": "Grande",
 "ac": 14,
 "acRaw": "14",
 "initiative": {
  "mod": 3,
  "score": 13
 },
 "hp": {
  "raw": "68 (8d10 + 24)",
  "average": 68,
  "formula": "8d10 + 24"
 },
 "speeds": {
  "caminando": 9.0,
  "volar": 15.0
 },
 "senses": {
  "raw": "visión en la oscuridad 18 m; Percepción pasiva 11",
  "passivePerception": 11
 },
 "languages": [
  "común"
 ],
 "challenge": {
  "raw": "3 (700 PX; BC +2)",
  "cr": 3,
  "xp": 700,
  "proficiencyBonus": 2
 },
 "abilities": {
  "fue": {
   "score": 17,
   "mod": 3,
   "save": 3
  },
  "des": {
   "score": 16,
   "mod": 3,
   "save": 3
  },
  "con": {
   "score": 17,
   "mod": 3,
   "save": 3
  },
  "int": {
   "score": 7,
   "mod": -2,
   "save": -2
  },
  "sab": {
   "score": 12,
   "mod": 1,
   "save": 1
  },
  "car": {
   "score": 8,
   "mod": -1,
   "save": -1
  }
 },
 "actions": [
  {
   "name": "Ataque múltiple",
   "md": "***Ataque múltiple.*** La mantícora realiza tres ataques de desgarro o con sus púas de cola en cualquier combinación.",
   "page": 347,
   "description": "La mantícora realiza tres ataques de desgarro o con sus púas de cola en cualquier combinación."
  },
  {
   "name": "Desgarro",
   "md": "***Desgarro.*** *Tirada de ataque cuerpo a cuerpo:* +5, alcance 1,5 m. *Acierto:* 7 (1d8 + 3) de daño cortante.",
   "page": 347,
   "description": "*Tirada de ataque cuerpo a cuerpo:* +5, alcance 1,5 m. *Acierto:* 7 (1d8 + 3) de daño cortante."
  },
  {
   "name": "Púas de cola",
   "md": "***Púas de cola.*** *Tirada de ataque a distancia:* +5, alcance 30/60 m. *Acierto:* 7 (1d8 + 3) de daño perforante.",
   "page": 347,
   "description": "*Tirada de ataque a distancia:* +5, alcance 30/60 m. *Acierto:* 7 (1d8 + 3) de daño perforante."
  }
 ]
}

=== gonzalorf/dnd-srd/data/processed/es/collections/monsters/mamut.json
{
 "id": "monster.mamut",
 "name": "Mamut",
 "source": {
  "book": "SRD 5.2.1 es",
  "page": 389
 },
 "context": [
  "Animales"
 ],
 "metaRaw": "Bestia Enorme, sin alineamiento",
 "type": "Bestia",
 "alignment": "sin alineamiento",
 "size": "Enorme",
 "ac": 13,
 "acRaw": "13",
 "initiative": {
  "mod": 2,
  "score": 12
 },
 "hp": {
  "raw": "126 (11d12 + 55)",
  "average": 126,
  "formula": "11d12 + 55"
 },
 "speeds": {
  "caminando": 15.0
 },
 "senses": {
  "raw": "Percepción pasiva 10",
  "passivePerception": 10
 },
 "languages": [
  "ninguno"
 ],
 "challenge": {
  "raw": "6 (2300 PX; BC +3)",
  "cr": 6,
  "xp": 2300,
  "proficiencyBonus": 3
 },
 "abilities": {
  "fue": {
   "score": 24,
   "mod": 7,
   "save": 10
  },
  "des": {
   "score": 9,
   "mod": -1,
   "save": -1
  },
  "con": {
   "score": 21,
   "mod": 5,
   "save": 8
  },
  "int": {
   "score": 3,
   "mod": -4,
   "save": -4
  },
  "sab": {
   "score": 11,
   "mod": 0,
   "save": 0
  },
  "car": {
   "score": 6,
   "mod": -2,
   "save": -2
  }
 },
 "actions": [
  {
   "name": "Ataque múltiple",
   "md": "***Ataque múltiple.*** El mamut realiza dos ataques con sus colmillos.",
   "page": 389,
   "description": "El mamut realiza dos ataques con sus colmillos."
  },
  {
   "name": "Colmillos",
   "md": "***Colmillos.*** *Tirada de ataque cuerpo a cuerpo:* +10, alcance 3 m. *Acierto:* 18 (2d10 + 7) de daño perforante. Si el objetivo es una criatura Enorme o más pequeña y el mamut recorre al menos 6 m en línea recta hacia ella justo antes de acertarle, tendrá el estado de derribada.",
   "page": 389,
   "description": "*Tirada de ataque cuerpo a cuerpo:* +10, alcance 3 m. *Acierto:* 18 (2d10 + 7) de daño perforante. Si el objetivo es una criatura Enorme o más pequeña y el mamut recorre al menos 6 m en línea recta hacia ella justo antes de acertarle, tendrá el estado de derribada."
  }
 ],
 "bonusActions": [
  {
   "name": "Arrollar",
   "md": "***Arrollar.*** *Tirada de salvación de Destreza:* CD 18, una criatura a 1,5 m o menos que tenga el estado de derribada. *Fallo:* 29 (4d10 + 7) de daño contundente. *Éxito:* la mitad del daño.",
   "page": 389,
   "description": "*Tirada de salvación de Destreza:* CD 18, una criatura a 1,5 m o menos que tenga el estado de derribada. *Fallo:* 29 (4d10 + 7) de daño contundente. *Éxito:* la mitad del daño."
  }
 ]
}

=== gonzalorf/dnd-srd/data/processed/es/collections/monsters/planetar.json
{
 "id": "monster.planetar",
 "name": "Planetar",
 "source": {
  "book": "SRD 5.2.1 es",
  "page": 360
 },
 "context": [
  "Planetar"
 ],
 "metaRaw": "Celestial Grande (ángel), legal bueno",
 "type": "Celestial",
 "alignment": "legal bueno",
 "size": "Grande",
 "tags": [
  "ángel"
 ],
 "ac": 19,
 "acRaw": "19",
 "initiative": {
  "mod": 10,
  "score": 20
 },
 "hp": {
  "raw": "262 (21d10 + 147)",
  "average": 262,
  "formula": "21d10 + 147"
 },
 "speeds": {
  "caminando": 12.0,
  "volar": 36.0
 },
 "skills": {
  "Percepción": 11
 },
 "senses": {
  "raw": "visión verdadera 36 m; Percepción pasiva 21",
  "passivePerception": 21
 },
 "languages": [
  "todos",
  "telepatía 36 m"
 ],
 "immunities": [
  "asustado",
  "cansancio",
  "hechizado"
 ],
 "resistances": [
  "radiante"
 ],
 "challenge": {
  "raw": "16 (15 000 PX; BC +5)",
  "cr": 16,
  "xp": 15000,
  "proficiencyBonus": 5
 },
 "abilities": {
  "fue": {
   "score": 24,
   "mod": 7,
   "save": 12
  },
  "des": {
   "score": 20,
   "mod": 5,
   "save": 5
  },
  "con": {
   "score": 24,
   "mod": 7,
   "save": 12
  },
  "int": {
   "score": 19,
   "mod": 4,
   "save": 4
  },
  "sab": {
   "score": 22,
   "mod": 6,
   "save": 11
  },
  "car": {
   "score": 25,
   "mod": 7,
   "save": 12
  }
 },
 "traits": [
  {
   "name": "Percepción divina",
   "md": "***Percepción divina.*** El planetar reconoce cualquier mentira que escuche.",
   "page": 360,
   "description": "El planetar reconoce cualquier mentira que escuche."
  },
  {
   "name": "Recuperación exaltada",
   "md": "***Recuperación exaltada.*** Si el planetar muere fuera del Monte Celestia, su cuerpo desaparece, obtiene un cuerpo nuevo al instante y revive con todos sus puntos de golpe en algún lugar del Monte Celestia.",
   "page": 360,
   "description": "Si el planetar muere fuera del Monte Celestia, su cuerpo desaparece, obtiene un cuerpo nuevo al instante y revive con todos sus puntos de golpe en algún lugar del Monte Celestia."
  },
  {
   "name": "Resistencia mágica",
   "md": "***Resistencia mágica.*** El planetar tiene ventaja en las tiradas de salvación contra conjuros y otros efectos mágicos.",
   "page": 360,
   "description": "El planetar tiene ventaja en las tiradas de salvación contra conjuros y otros efectos mágicos."
  }
 ],
 "actions": [
  {
   "name": "Ataque múltiple",
   "md": "***Ataque múltiple.*** El planetar realiza tres ataques con su espada radiante o emplea su estallido sagrado dos veces.",
   "page": 360,
   "description": "El planetar realiza tres ataques con su espada radiante o emplea su estallido sagrado dos veces."
  },
  {
   "name": "Espada radiante",
   "md": "***Espada radiante.*** *Tirada de ataque cuerpo a cuerpo:* +12, alcance 3 m. *Acierto:* 14 (2d6 + 7) de daño cortante más 18 (4d8) de daño radiante.",
   "page": 360,
   "description": "*Tirada de ataque cuerpo a cuerpo:* +12, alcance 3 m. *Acierto:* 14 (2d6 + 7) de daño cortante más 18 (4d8) de daño radiante."
  },
  {
   "name": "Estallido sagrado",
   "md": "***Estallido sagrado.*** *Tirada de salvación de Destreza:* CD 20, todos los enemigos en una esfera de 6 m de radio centrada en un punto que el planetar pueda ver",
   "page": 360,
   "description": "*Tirada de salvación de Destreza:* CD 20, todos los enemigos en una esfera de 6 m de radio centrada en un punto que el planetar pueda ver"
  },
  {
   "name": null,
   "md": "a 36 m o menos. *Fallo:* 24 (7d6) de daño radiante. *Éxito:* la mitad del daño.",
   "page": 360
  },
  {
   "name": "Lanzamiento de conjuros",
   "md": "***Lanzamiento de conjuros.*** El planetar lanza uno de los siguientes conjuros, que no requiere componentes materiales y utiliza el Carisma como aptitud mágica (CD de salvación de conjuros 20):",
   "page": 360,
   "description": "El planetar lanza uno de los siguientes conjuros, que no requiere componentes materiales y utiliza el Carisma como aptitud mágica (CD de salvación de conjuros 20):"
  },
  {
   "name": null,
   "md": "A voluntad: *detectar el bien y el mal* 1/día cada uno: *alzar a los muertos*, *comunión*, *controlar el clima*, *disipar el bien y el mal*",
   "page": 360
  }
 ],
 "bonusActions": [
  {
   "name": "Auxilio divino",
   "md": "***Auxilio divino (2/día).*** El planetar lanza *curar heridas*, *invisibilidad*, *levantar maldición* o *restablecimiento menor* usando la misma aptitud mágica que para su lanzamiento de conjuros.",
   "page": 360,
   "description": "El planetar lanza *curar heridas*, *invisibilidad*, *levantar maldición* o *restablecimiento menor* usando la misma aptitud mágica que para su lanzamiento de conjuros.",
   "uses": "2/día"
  }
 ],
 "refs": [
  "spell.detectar-el-bien-y-el-mal",
  "spell.alzar-a-los-muertos",
  "spell.comunion",
  "spell.controlar-el-clima",
  "spell.disipar-el-bien-y-el-mal",
  "spell.curar-heridas",
  "spell.invisibilidad",
  "spell.levantar-maldicion",
  "spell.restablecimiento-menor"
 ]
}

=== gonzalorf/dnd-srd/data/processed/es/collections/monsters/enjambre-de-murcielagos.json
{
 "id": "monster.enjambre-de-murcielagos",
 "name": "Enjambre de murciélagos",
 "source": {
  "book": "SRD 5.2.1 es",
  "page": 384
 },
 "context": [
  "Animales"
 ],
 "metaRaw": "Enjambre Grande de bestias Diminutas, sin alineamiento",
 "type": "Enjambre de bestias Diminutas",
 "alignment": "sin alineamiento",
 "size": "Grande",
 "ac": 12,
 "acRaw": "12",
 "initiative": {
  "mod": 2,
  "score": 12
 },
 "hp": {
  "raw": "11 (2d10)",
  "average": 11,
  "formula": "2d10"
 },
 "speeds": {
  "caminando": 1.5,
  "volar": 9.0
 },
 "senses": {
  "raw": "visión ciega 18 m; Percepción pasiva 11",
  "passivePerception": 11
 },
 "languages": [
  "ninguno"
 ],
 "immunities": [
  "agarrado",
  "apresado",
  "asustado",
  "aturdido",
  "derribado",
  "hechizado",
  "paralizado",
  "petrificado"
 ],
 "resistances": [
  "contundente",
  "cortante",
  "perforante"
 ],
 "challenge": {
  "raw": "1/4 (50 PX; BC +2)",
  "cr": 0.25,
  "xp": 50,
  "proficiencyBonus": 2
 },
 "abilities": {
  "fue": {
   "score": 5,
   "mod": -3,
   "save": -3
  },
  "des": {
   "score": 15,
   "mod": 2,
   "save": 2
  },
  "con": {
   "score": 10,
   "mod": 0,
   "save": 0
  },
  "int": {
   "score": 2,
   "mod": -4,
   "save": -4
  },
  "sab": {
   "score": 12,
   "mod": 1,
   "save": 1
  },
  "car": {
   "score": 4,
   "mod": -3,
   "save": -3
  }
 },
 "traits": [
  {
   "name": "Enjambre",
   "md": "***Enjambre.*** El enjambre puede ocupar el espacio de otra criatura y viceversa, y es capaz de atravesar cualquier abertura por la que quepa un murciélago Diminuto. El enjambre no puede recuperar puntos de golpe ni obtener puntos de golpe temporales.",
   "page": 384,
   "description": "El enjambre puede ocupar el espacio de otra criatura y viceversa, y es capaz de atravesar cualquier abertura por la que quepa un murciélago Diminuto. El enjambre no puede recuperar puntos de golpe ni obtener puntos de golpe temporales."
  }
 ],
 "actions": [
  {
   "name": "Mordiscos",
   "md": "***Mordiscos.*** *Tirada de ataque cuerpo a cuerpo:* +4, alcance 1,5 m. *Acierto:* 5 (2d4) de daño perforante o 2 (1d4) de daño perforante si el enjambre está maltrecho.",
   "page": 384,
   "description": "*Tirada de ataque cuerpo a cuerpo:* +4, alcance 1,5 m. *Acierto:* 5 (2d4) de daño perforante o 2 (1d4) de daño perforante si el enjambre está maltrecho."
  }
 ]
}

=== gonzalorf/dnd-srd/data/processed/es/collections/monsters/dretch.json
{
 "id": "monster.dretch",
 "name": "Dretch",
 "source": {
  "book": "SRD 5.2.1 es",
  "page": 317
 },
 "context": [
  "Dretch"
 ],
 "metaRaw": "Infernal Pequeño (demonio), caótico malvado",
 "type": "Infernal",
 "alignment": "caótico malvado",
 "size": "Pequeño",
 "tags": [
  "demonio"
 ],
 "ac": 11,
 "acRaw": "11",
 "initiative": {
  "mod": 0,
  "score": 10
 },
 "hp": {
  "raw": "18 (4d6 + 4)",
  "average": 18,
  "formula": "4d6 + 4"
 },
 "speeds": {
  "caminando": 6.0
 },
 "senses": {
  "raw": "visión en la oscuridad 18 m; Percepción pasiva 9",
  "passivePerception": 9
 },
 "languages": [
  "abisal",
  "telepatía 18 m (solo funciona con criaturas que entiendan abisal)"
 ],
 "immunities": [
  "veneno",
  "envenenado"
 ],
 "resistances": [
  "frío",
  "fuego",
  "relámpago"
 ],
 "challenge": {
  "raw": "1/4 (50 PX; BC +2)",
  "cr": 0.25,
  "xp": 50,
  "proficiencyBonus": 2
 },
 "abilities": {
  "fue": {
   "score": 12,
   "mod": 1,
   "save": 1
  },
  "des": {
   "score": 11,
   "mod": 0,
   "save": 0
  },
  "con": {
   "score": 12,
   "mod": 1,
   "save": 1
  },
  "int": {
   "score": 5,
   "mod": -3,
   "save": -3
  },
  "sab": {
   "score": 8,
   "mod": -1,
   "save": -1
  },
  "car": {
   "score": 3,
   "mod": -4,
   "save": -4
  }
 },
 "actions": [
  {
   "name": "Desgarro",
   "md": "***Desgarro.*** *Tirada de ataque cuerpo a cuerpo:* +3, alcance 1,5 m. *Acierto:* 4 (1d6 + 1) de daño cortante.",
   "page": 317,
   "description": "*Tirada de ataque cuerpo a cuerpo:* +3, alcance 1,5 m. *Acierto:* 4 (1d6 + 1) de daño cortante."
  },
  {
   "name": "Nube fétida",
   "md": "***Nube fétida (1/día).*** *Tirada de salvación de Constitución:* CD 11, todas las criaturas en una emanación de 3 m que se origina en el dretch. *Fallo:* el objetivo tendrá el estado de envenenado hasta el final de su siguiente turno. Mientras esté envenenada, la criatura podrá realizar una acción o una acción adicional en su turno, pero no ambas, y no podrá llevar a cabo reacciones.",
   "page": 317,
   "description": "*Tirada de salvación de Constitución:* CD 11, todas las criaturas en una emanación de 3 m que se origina en el dretch. *Fallo:* el objetivo tendrá el estado de envenenado hasta el final de su siguiente turno. Mientras esté envenenada, la criatura podrá realizar una acción o una acción adicional en su turno, pero no ambas, y no podrá llevar a cabo reacciones.",
   "uses": "1/día"
  }
 ]
}

=== gonzalorf/dnd-srd/data/processed/es/collections/monsters/cuervo.json
{
 "id": "monster.cuervo",
 "name": "Cuervo",
 "source": {
  "book": "SRD 5.2.1 es",
  "page": 383
 },
 "context": [
  "Animales"
 ],
 "metaRaw": "Bestia Diminuta, sin alineamiento",
 "type": "Bestia",
 "alignment": "sin alineamiento",
 "size": "Diminuto",
 "ac": 12,
 "acRaw": "12",
 "initiative": {
  "mod": 2,
  "score": 12
 },
 "hp": {
  "raw": "2 (1d4)",
  "average": 2,
  "formula": "1d4"
 },
 "speeds": {
  "caminando": 3.0,
  "volar": 15.0
 },
 "skills": {
  "Percepción": 3
 },
 "senses": {
  "raw": "Percepción pasiva 13",
  "passivePerception": 13
 },
 "languages": [
  "ninguno"
 ],
 "challenge": {
  "raw": "0 (10 PX; BC +2)",
  "cr": 0,
  "xp": 10,
  "proficiencyBonus": 2
 },
 "abilities": {
  "fue": {
   "score": 2,
   "mod": -4,
   "save": -4
  },
  "des": {
   "score": 14,
   "mod": 2,
   "save": 2
  },
  "con": {
   "score": 10,
   "mod": 0,
   "save": 0
  },
  "int": {
   "score": 5,
   "mod": -3,
   "save": -3
  },
  "sab": {
   "score": 13,
   "mod": 1,
   "save": 1
  },
  "car": {
   "score": 6,
   "mod": -2,
   "save": -2
  }
 },
 "traits": [
  {
   "name": "Imitación",
   "md": "***Imitación.*** El cuervo puede imitar sonidos sencillos que haya escuchado, como un susurro o un trino. Alguien que lo escuche podrá darse cuenta de que son imitaciones si supera una prueba de Sabiduría (Perspicacia) con CD 10.",
   "page": 383,
   "description": "El cuervo puede imitar sonidos sencillos que haya escuchado, como un susurro o un trino. Alguien que lo escuche podrá darse cuenta de que son imitaciones si supera una prueba de Sabiduría (Perspicacia) con CD 10."
  }
 ],
 "actions": [
  {
   "name": "Pico",
   "md": "***Pico.*** *Tirada de ataque cuerpo a cuerpo:* +4, alcance 1,5 m. *Acierto:* 1 de daño perforante.",
   "page": 383,
   "description": "*Tirada de ataque cuerpo a cuerpo:* +4, alcance 1,5 m. *Acierto:* 1 de daño perforante."
  }
 ]
}
